using System.Collections.Generic;

namespace KikuCaption.App.Localization;

/// <summary>
/// The bilingual string tables (UI-R3 localization). Keys are stable identifiers; the two tables
/// must contain exactly the same keys — <c>LocalizationResourceTests</c> enforces this. Caption
/// text, meeting files and logs are never translated here. Internal language codes (ja/zh/en) stay
/// stable; only their display names differ per row.
/// </summary>
public static class LocalizedStrings
{
    public const string ZhCN = "zh-CN";
    public const string EnUS = "en-US";
    public const string JaJP = "ja-JP";

    public static IReadOnlyList<string> SupportedCultures { get; } = new[] { ZhCN, EnUS, JaJP };

    private static readonly IReadOnlyDictionary<string, string> Zh = new Dictionary<string, string>
    {
        // Top navigation
        ["Nav.Home"] = "首页",
        ["Nav.Audio"] = "音频",
        ["Nav.Dictionary"] = "词典",
        ["Nav.Settings"] = "设置",
        ["Nav.EnvironmentMenu"] = "环境菜单",
        ["Nav.EnvironmentStatus"] = "环境状态，查看环境详情",
        ["Nav.EnvironmentDetail"] = "环境详情",
        ["Nav.RecheckEnvironment"] = "重新检查环境",

        // Environment health
        ["Env.Health.Checking"] = "正在检查…",
        ["Env.Health.Healthy"] = "环境正常",
        ["Env.Health.Degraded"] = "部分功能受限",
        ["Env.Health.Blocked"] = "关键环境缺失",
        ["Env.Health.Unknown"] = "尚未检查",
        ["Env.Title"] = "运行环境",
        ["Env.Recheck"] = "重新检查",
        ["Env.OpenSettings"] = "打开设置",
        ["Env.CopyDiagnostics"] = "复制诊断信息",

        // Home control bar
        ["Home.RecognitionLanguage"] = "识别语言",
        ["Home.Translation"] = "翻译",
        ["Home.StartMeeting"] = "开始会议",
        // UI-R5B system tray
        ["Tray.StartSession"] = "开始会话",
        ["Tray.StopSession"] = "停止会话",
        ["Tray.ShowOverlay"] = "显示字幕浮窗",
        ["Tray.HideOverlay"] = "隐藏字幕浮窗",
        ["Tray.OpenSettings"] = "打开设置",
        ["Tray.OpenMainWindow"] = "打开主窗口",
        ["Tray.Exit"] = "退出",
        ["Tray.Status.Idle"] = "空闲",
        ["Tray.Status.Starting"] = "正在启动",
        ["Tray.Status.Recording"] = "录制中",
        ["Tray.Status.Stopping"] = "正在停止",
        ["Tray.Status.Error"] = "错误",
        ["Tray.MinimizedHint"] = "KikuCaption 仍在系统托盘中运行。",
        ["Tray.SessionError"] = "会话发生错误，请打开主窗口查看详情。",
        ["General.MinimizeToTray"] = "最小化时隐藏到系统托盘",
        ["General.CloseToTray"] = "关闭主窗口时隐藏到系统托盘",
        ["Home.Stop"] = "停止",
        ["Home.ShowOverlay"] = "显示浮窗",
        ["Home.HideOverlay"] = "隐藏浮窗",
        ["Home.NotConfiguredConfigure"] = "未配置，点此设置",
        ["Home.LanguageTooltip"] = "选择识别语言（会话运行中不可更改）",

        // Session card
        ["Session.Title"] = "当前会话",
        ["Session.State"] = "状态",
        ["Session.Elapsed"] = "已运行",
        ["Session.Language"] = "识别语言",
        ["Session.Direction"] = "翻译方向",
        ["Session.Recording"] = "录制",

        // Timeline
        ["Timeline.HeaderPrefix"] = "会议字幕（全程 ",
        ["Timeline.HeaderSuffix"] = " 条）",
        ["Timeline.Hint"] = "最早在上、最新在下；上滑查看历史不会被打断。",
        ["Timeline.Menu"] = "更多操作",
        ["Timeline.LoadRecent"] = "加载最近会话",
        ["Timeline.ClearDisplay"] = "清空显示",
        ["Timeline.EmptyTitle"] = "还没有会议字幕",
        ["Timeline.EmptyHint"] = "点击右上角“开始会议”，即可开始录制并实时显示字幕。",
        ["Timeline.Recognizing"] = "正在识别：",

        // Start-meeting dialog
        ["StartDialog.Title"] = "开始会议",
        ["StartDialog.Intro"] = "选择录制目标并开始。字幕与录屏会保存到下方输出目录。",
        ["StartDialog.CaptureTarget"] = "录制目标：",
        ["StartDialog.WholeScreen"] = "整个屏幕",
        ["StartDialog.SpecificWindow"] = "指定窗口",
        ["StartDialog.RefreshWindows"] = "刷新窗口",
        ["StartDialog.AudioSection"] = "音频输入",
        ["StartDialog.RecordSystemAudio"] = "录制系统声音",
        ["StartDialog.RecordMicrophone"] = "录制并识别我的麦克风",
        ["StartDialog.MicDevice"] = "麦克风设备",
        ["StartDialog.RefreshDevices"] = "刷新设备",
        ["StartDialog.InputLevel"] = "输入音量",
        ["StartDialog.MicTooltip"] = "麦克风识别语言跟随当前会议识别语言。使用音箱时，麦克风可能再次收到系统声音并产生重复字幕，建议使用耳机。",
        ["StartDialog.NoAudioInput"] = "请至少选择一种音频输入（系统声音或麦克风）。",
        ["StartDialog.MicUnavailable"] = "所选麦克风不可用。可仅使用系统声音继续，或返回选择其他设备。",
        ["StartDialog.OutputLocation"] = "输出位置",
        ["StartDialog.Cancel"] = "取消",
        ["StartDialog.Start"] = "开始会议",
        ["StartDialog.WindowRequired"] = "已选择“指定窗口”，请先选择要录制的窗口。",

        // Audio page
        ["Audio.Title"] = "音频工具",
        ["Audio.Intro"] = "用于验证系统音频采集与本地识别的诊断工具，与会议流程独立。",
        ["Audio.CaptureHeader"] = "系统音频捕获",
        ["Audio.CaptureIntro"] = "将系统输出声音录制为 16 kHz / 单声道 / 16-bit PCM 的 WAV。请在捕获期间播放音频。",
        ["Audio.StartCapture"] = "开始捕获…",
        ["Audio.Stop"] = "停止",
        ["Audio.RecognizeHeader"] = "本地语音识别",
        ["Audio.RecognizeIntro"] = "用本地 faster-whisper 识别一个 WAV 文件，输出带时间戳的文本。首次会加载模型。",
        ["Audio.RecognitionLanguage"] = "识别语言：",
        ["Audio.RecognizeWav"] = "识别 WAV 文件…",

        // Settings shell
        ["Settings.Title"] = "设置",
        ["Settings.Tab.General"] = "常用",
        ["Settings.Tab.Subtitle"] = "字幕",
        ["Settings.Tab.Translation"] = "翻译",
        ["Settings.RestoreDefaults"] = "恢复默认设置",
        ["Settings.Save"] = "保存",
        ["Settings.Saved"] = "设置已保存。",
        ["Settings.SaveFailed"] = "保存设置失败，请重试。",
        ["Settings.NextMeetingHint"] = "会话进行中，识别语言/录制目标等更改将于下次会议生效。",

        // General settings
        ["General.UiLanguage"] = "界面语言",
        ["General.DefaultRecognitionLanguage"] = "默认识别语言",
        ["General.OutputDirectory"] = "会话输出目录",
        ["General.Browse"] = "浏览…",
        ["General.LoadRecentOnStartup"] = "启动时加载最近会议",
        ["General.DefaultTranslationEnabled"] = "默认启用翻译",
        ["General.DefaultRecordingTarget"] = "默认录制目标",
        ["General.LogRetentionDays"] = "日志保留天数",

        // Subtitle settings
        ["Subtitle.DefaultShowOverlay"] = "默认显示浮窗",
        ["Subtitle.FontSize"] = "字号",
        ["Subtitle.FontFamily"] = "字体",
        ["Subtitle.BackgroundOpacity"] = "背景透明度",
        ["Subtitle.MaxLines"] = "最大行数",
        ["Subtitle.Topmost"] = "置顶",
        ["Subtitle.ClickThrough"] = "鼠标穿透",
        ["Subtitle.ShowOriginal"] = "显示原文",
        ["Subtitle.ShowTranslation"] = "显示翻译",
        ["Subtitle.OriginalColor"] = "原文颜色",
        ["Subtitle.TranslationColor"] = "翻译颜色",
        ["Subtitle.PartialOpacity"] = "临时文本淡化",
        ["Subtitle.Preview"] = "实时预览",
        ["Subtitle.RestoreDefaults"] = "恢复默认值",
        ["Subtitle.SampleOriginal"] = "これはサンプル字幕です。",
        ["Subtitle.SampleTranslation"] = "这是一条示例字幕。",
        ["Subtitle.SamplePartial"] = "正在识别的临时文本…",

        // Translation settings
        ["Tr.Header"] = "翻译",
        ["Tr.Intro"] = "仅将 final 字幕文本发送到公司内部 OpenAI 兼容 API 翻译。不发送音频、partial 或视频。API Key 以 Windows DPAPI 加密保存在本机，不写入配置或日志。",
        ["Tr.Enable"] = "启用翻译",
        ["Tr.AuthMode"] = "认证模式",
        ["Tr.HeaderName"] = "Header 名",
        ["Tr.ApiKey"] = "API Key",
        ["Tr.SaveKey"] = "保存密钥",
        ["Tr.ClearKey"] = "清除密钥",
        ["Tr.Proxy"] = "代理（可选）",
        ["Tr.TestConnection"] = "测试连接",
        ["Tr.SaveSettings"] = "保存设置",
        ["Tr.SourceLanguage"] = "来源语言",
        ["Tr.SourceFollow"] = "跟随识别语言",
        ["Tr.Timeout"] = "请求超时（秒）",
        ["Tr.MaxRetries"] = "最大重试次数",
        ["Tr.TargetLanguage"] = "目标语言",
        ["Tr.CurrentDirection"] = "当前方向",
        ["Tr.SameLanguageNote"] = "来源语言与目标语言相同，无需翻译。",
        ["Tr.TestSameLanguage"] = "来源与目标相同，请选择不同的目标语言后再测试。",
        ["Home.NoTranslationNeeded"] = "无需翻译：",
        ["Home.Translating"] = "翻译中：",
        ["Tr.Test.Testing"] = "正在测试连接……",
        ["Tr.Test.Success"] = "连接成功。",
        ["Tr.Test.Empty"] = "连接成功，但返回为空。",
        ["Tr.Test.Auth"] = "认证失败（请检查 API Key / 认证模式）。",
        ["Tr.Test.RateLimited"] = "被限流（429）。",
        ["Tr.Test.Unavailable"] = "服务暂时不可用（5xx）。",
        ["Tr.Test.Timeout"] = "连接超时。",
        ["Tr.Test.Network"] = "网络错误。",
        ["Tr.Test.InvalidConfig"] = "配置无效（Endpoint / HTTPS / Key）。",
        ["Tr.Test.Failed"] = "连接失败。",
        ["Tr.SettingsSaved"] = "翻译设置已保存（Endpoint 已加密，下次打开自动读取）。",
        ["Tr.SettingsSaveFailed"] = "保存翻译设置失败。",
        ["Tr.KeyConfigured"] = "API Key：已配置",
        ["Tr.KeyNotConfigured"] = "API Key：未配置",
        ["Tr.QueueIdle"] = "空闲",
        ["Tr.QueueBusy"] = "翻译队列：{0} 条处理中",
        ["Tr.LastError"] = "最近错误：{0}",

        // Confirm dialogs
        ["Confirm.CloseWhileRecording"] = "会议正在录制中。关闭前将安全停止并保存 MP4 与字幕（不会强制结束进程）。是否继续关闭？",
        ["Common.AppName"] = "KikuCaption",
        ["Common.NextMeeting"] = "下次会议生效",
        ["Common.AfterRestart"] = "下次启动生效",

        // Session state (from the session state machine; internal enum stays stable)
        ["Session.State.Idle"] = "空闲",
        ["Session.State.Preflight"] = "预检中",
        ["Session.State.Starting"] = "启动中",
        ["Session.State.Running"] = "运行中",
        ["Session.State.Stopping"] = "停止中",
        ["Session.State.Completed"] = "已完成",
        ["Session.State.Faulted"] = "已故障",
        ["Session.State.Recovering"] = "恢复中",

        // Recording status
        ["Recorder.Ready"] = "就绪",
        ["Recorder.NoFFmpeg"] = "未找到 FFmpeg（仅字幕，不录屏）",
        ["Recorder.NoFFmpegShort"] = "未找到 FFmpeg，仅字幕（未录屏）。",
        ["Recorder.Unavailable"] = "录屏不可用（预检警告）——本次仅字幕继续。",
        ["Recorder.Recording"] = "录屏中（编码器 {0}）",
        ["Recorder.Failed"] = "录屏失败，仅字幕。",
        ["Recorder.Done"] = "录屏完成（{0}，{1} MB）",
        ["Recorder.Incomplete"] = "录屏可能不完整（详见提示）。",

        // Health
        ["Health.Normal"] = "运行正常",
        ["Health.HighCpu"] = "CPU 偏高",
        ["Health.LowDisk"] = "磁盘不足",

        // Session status line
        ["Status.Idle"] = "未开始。开始后将捕获系统声音并显示实时字幕。",
        ["Status.Loading"] = "正在启动 Worker 并加载模型（首次约 1–2 秒）……",
        ["Status.Running"] = "实时字幕运行中（语言：{0}）。",
        ["Status.Stopping"] = "正在停止并保存……",
        ["Status.Stopped"] = "已停止。字幕已保存到输出目录。",
        ["Status.PreflightBlocked"] = "预检存在阻断项，未开始。",
        ["Status.StartFailed"] = "启动失败，详见提示与日志。",
        ["Status.Faulted"] = "已因错误停止。已保存的字幕仍在输出目录。",

        // User-facing error titles (technical detail may be appended, not localized)
        ["Error.StartFailed"] = "启动失败（已回滚已启动模块，已保存字幕保留）：",
        ["Error.Fault"] = "实时字幕中断：",
        ["Error.PreflightBlocked"] = "预检未通过：",
        ["Error.WindowRequired"] = "已选择“指定窗口”，请先选择要录制的窗口。",
        ["Error.DiskLow"] = "磁盘空间不足，已安全停止接收新字幕。",
        ["Error.SaveCaptionFailed"] = "保存字幕失败：",
        ["Error.RecordingStartFailed"] = "录屏启动失败：",
        ["Error.RecordingStopFailed"] = "停止录屏出错：",

        // Timeline dynamic
        ["Timeline.NewMessages"] = "有 {0} 条新字幕 ↓",
        ["Timeline.Translating"] = "翻译中…",
        ["Timeline.TranslationFailed"] = "⚠ 翻译失败（已保留原文）",
        ["Overlay.Translating"] = "翻译中…",

        // Environment page messages
        ["Env.Msg.Checking"] = "正在检查运行环境……",
        ["Env.Msg.Healthy"] = "运行环境检查完成，未发现问题。",
        ["Env.Msg.Degraded"] = "字幕可正常使用；部分非关键能力（录屏或翻译）当前不可用（详见下方）。",
        ["Env.Msg.Blocked"] = "缺少关键依赖，核心字幕功能暂时无法开始（详见下方）。程序不会崩溃。",
        ["Env.Msg.Cancelled"] = "环境检查已取消。",
        ["Env.Msg.Error"] = "环境检查过程出错，详见日志。",
        ["Env.Msg.NotChecked"] = "尚未检查运行环境。",
        ["Env.LastChecked"] = "最近检查：{0}",
        ["Env.Copied"] = "已复制诊断信息（不含任何密钥或字幕内容）。",
        ["Env.CopyFailed"] = "复制诊断信息失败，请重试。",

        // Environment item status badges + dependency display names
        ["Env.Status.Ok"] = "正常",
        ["Env.Status.Warning"] = "注意",
        ["Env.Status.Missing"] = "缺失",
        ["Env.Status.Error"] = "错误",
        ["Env.Status.Unknown"] = "未知",
        ["Env.Dep.DotNetRuntime"] = ".NET 运行时",
        ["Env.Dep.Python"] = "Python",
        ["Env.Dep.WhisperWorker"] = "faster-whisper Worker",
        ["Env.Dep.WhisperModel"] = "Whisper 模型",
        ["Env.Dep.FFmpeg"] = "FFmpeg",
        ["Env.Dep.FFprobe"] = "FFprobe",
        ["Env.Dep.AudioOutputDevice"] = "音频输出设备",
        ["Env.Dep.OutputDirectory"] = "输出目录写入权限",
        ["Env.Dep.DiskSpace"] = "可用磁盘空间",
        ["Env.Dep.TranslationApi"] = "翻译 API 配置",

        // Environment probe messages (probes emit codes; App localizes — UI-R3.1)
        ["EnvMsg.DotNet.Ok"] = "已在 .NET 10 或更高版本运行时上运行。",
        ["EnvMsg.DotNet.Old"] = "当前运行时低于 .NET 10。",
        ["EnvRem.DotNet.Old"] = "请安装 .NET 10 运行时 / SDK：https://dotnet.microsoft.com/download/dotnet/10.0",
        ["EnvMsg.Python.Ok"] = "已检测到可用的 Python 解释器（推荐 3.11）。",
        ["EnvMsg.Python.OkOldish"] = "已检测到 Python，但版本可能与 faster-whisper 依赖不完全兼容，推荐使用 3.11。",
        ["EnvMsg.Python.Missing"] = "未检测到 Python。本地语音识别（faster-whisper）将无法使用。",
        ["EnvRem.Python.Missing"] = "请安装 Python 3.11（勾选加入 PATH）：https://www.python.org/downloads/",
        ["EnvMsg.FFmpeg.Missing"] = "未找到 ffmpeg.exe。录屏与音视频封装将不可用，但字幕识别不受影响。",
        ["EnvMsg.FFmpeg.NotRunnable"] = "找到 ffmpeg.exe，但无法运行（可能损坏或架构不匹配）。",
        ["EnvMsg.FFmpeg.Ok"] = "已检测到可运行的 FFmpeg。",
        ["EnvRem.FFmpeg.Missing"] = "将 ffmpeg.exe 放入应用目录下的 tools/ffmpeg，或在设置中指定路径，或加入系统 PATH。",
        ["EnvRem.FFmpeg.NotRunnable"] = "请替换为可用的 FFmpeg 构建（64 位 Windows 版）。",
        ["EnvMsg.FFprobe.MissingBeside"] = "找到 ffmpeg.exe，但同目录缺少 ffprobe.exe，录屏封装将不完整。",
        ["EnvMsg.FFprobe.MissingPair"] = "未找到 ffprobe.exe（FFmpeg 工具对缺失）。录屏不可用，字幕识别不受影响。",
        ["EnvMsg.FFprobe.NotRunnable"] = "找到 ffprobe.exe，但无法运行（可能损坏或架构不匹配）。",
        ["EnvMsg.FFprobe.Ok"] = "已检测到可运行的 FFprobe。",
        ["EnvRem.FFprobe.Missing"] = "请将 ffprobe.exe 与 ffmpeg.exe 放在同一目录（成对提供）。",
        ["EnvRem.FFprobe.NotRunnable"] = "请替换为可用的 FFmpeg 构建（含配套 ffprobe.exe）。",
        ["EnvMsg.Disk.Info"] = "驱动器 {0} 当前可用 {1} GB（最低要求 {2} GB）。",
        ["EnvMsg.Disk.Error"] = "无法读取驱动器 {0} 的可用空间。",
        ["EnvRem.Disk.Low"] = "可用磁盘空间偏低，录制前请清理磁盘或更换输出目录。",
        ["EnvRem.Disk.Error"] = "请确认输出目录所在驱动器存在且可访问。",
        ["EnvMsg.Worker.NoScript"] = "未找到 whisper_worker 脚本，实时字幕与本地识别无法运行。",
        ["EnvMsg.Worker.NoPython"] = "找到 worker 脚本，但未找到 Python 解释器。",
        ["EnvMsg.Worker.Ok"] = "已找到本地识别 Worker 脚本与 Python 解释器。",
        ["EnvRem.Worker.NoScript"] = "请建立 Python 环境并确保 whisper_worker 脚本存在（参见项目说明）。",
        ["EnvRem.Worker.NoPython"] = "请在设置中指定 Python 可执行文件，或将其加入系统 PATH。",
        ["EnvMsg.Model.Ok"] = "已检测到 Whisper 模型缓存。",
        ["EnvMsg.Model.Missing"] = "未找到 Whisper 模型缓存，首次识别前需要下载模型。",
        ["EnvRem.Model.Missing"] = "请按项目说明下载模型到缓存目录（默认 models/whisper）。",
        ["EnvMsg.Audio.EnumFail"] = "无法枚举音频输出设备。",
        ["EnvMsg.Audio.Missing"] = "未检测到默认音频输出设备，无法采集系统声音。",
        ["EnvMsg.Audio.Ok"] = "已检测到默认音频输出设备。",
        ["EnvRem.Audio.EnumFail"] = "请检查 Windows 声音设置中的输出设备。",
        ["EnvRem.Audio.Missing"] = "请在 Windows 声音设置中启用一个输出设备后重新检查。",
        ["EnvMsg.Output.Ok"] = "会话输出目录可写。",
        ["EnvMsg.Output.NotWritable"] = "无法在输出目录写入，字幕与录制文件将无法保存。",
        ["EnvRem.Output.NotWritable"] = "请在设置中改用一个可写目录，或授予该目录写入权限。",
        ["EnvMsg.Trans.Disabled"] = "翻译未启用（可在设置中开启）。",
        ["EnvMsg.Trans.Ok"] = "翻译已配置并可用。",
        ["EnvMsg.Trans.Incomplete"] = "翻译已启用但配置不完整（缺少：{0}）。字幕不受影响。",
        ["EnvRem.Trans.Incomplete"] = "请在翻译设置中补全配置；密钥通过 Windows DPAPI 本地加密保存。",

        // Localized display for internal enum values (value stays screen/window, Bearer/None…)
        ["Capture.screen"] = "整个屏幕",
        ["Capture.window"] = "指定窗口",
        ["Auth.Bearer"] = "Bearer",
        ["Auth.ApiKeyHeader"] = "API Key 请求头",
        ["Auth.None"] = "无",

        // Speech dictionary (UI-R4B)
        ["Dict.Title"] = "专业术语词典",
        ["Dict.Disclaimer"] = "词典用于提高模型识别这些术语的概率，但不保证每次都能完全正确识别。",
        ["Dict.LanguageFilter"] = "识别语言",
        ["Dict.New"] = "新建",
        ["Dict.Duplicate"] = "复制",
        ["Dict.Delete"] = "删除",
        ["Dict.SetActive"] = "设为当前",
        ["Dict.Save"] = "保存",
        ["Dict.RestoreBuiltIn"] = "恢复默认内容",
        ["Dict.ActiveMarker"] = "当前",
        ["Dict.BuiltInMarker"] = "内置",
        ["Dict.Name"] = "名称",
        ["Dict.Language"] = "识别语言",
        ["Dict.InitialPrompt"] = "初始提示",
        ["Dict.Hotwords"] = "热词术语",
        ["Dict.HotwordsHint"] = "每行一个术语",
        ["Dict.ItemsLabel"] = "条目数",
        ["Dict.CharsLabel"] = "总字符",
        ["Dict.PromptCharsLabel"] = "提示字符",
        ["Dict.AppliesNextMeeting"] = "切换将于下次会议生效。",
        ["Dict.LocalStorageNote"] = "词典保存在本机当前用户目录中，不会发送给翻译 API。",
        ["Dict.BuiltInReadOnlyHint"] = "内置词典为只读，如需修改请点击“复制”创建用户词典。",
        ["Dict.NewName"] = "新词典",
        ["Dict.CopySuffix"] = "副本",
        ["Dict.Saved"] = "已保存",
        ["Dict.Deleted"] = "已删除",
        ["Dict.Restored"] = "已恢复默认内容",
        ["Dict.UnsavedTitle"] = "未保存的更改",
        ["Dict.UnsavedMessage"] = "当前词典有未保存的更改。是＝保存，否＝放弃，取消＝返回编辑。",
        ["Dict.DeleteConfirmTitle"] = "删除词典",
        ["Dict.DeleteConfirmMessage"] = "确定删除该词典吗？此操作无法撤销。",
        ["Dict.DeleteActiveMessage"] = "该词典是当前语言的当前词典，删除后将自动回退到内置默认词典。确定删除吗？",
        ["Dict.BuiltIn.ja"] = "默认日语技术词典",
        ["Dict.BuiltIn.zh"] = "默认中文技术词典",
        ["Dict.Error.NameRequired"] = "名称不能为空。",
        ["Dict.Error.NameLength"] = "名称长度 {0} 超过上限 {1}。",
        ["Dict.Error.NameDuplicate"] = "同一识别语言下已存在同名词典「{0}」。",
        ["Dict.Error.HotwordLength"] = "术语「{0}」长度 {1} 超过上限 {2}。",
        ["Dict.Error.HotwordCount"] = "术语条目数 {0} 超过上限 {1}。",
        ["Dict.Error.HotwordTotal"] = "术语总字符数 {0} 超过上限 {1}。",
        ["Dict.Error.PromptLength"] = "初始提示长度 {0} 超过上限 {1}。",

        // Language display names (culture-dependent: Chinese UI uses endonyms)
        ["Lang.ja"] = "日本語",
        ["Lang.zh"] = "中文",
        ["Lang.en"] = "English"
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["Nav.Home"] = "Home",
        ["Nav.Audio"] = "Audio",
        ["Nav.Dictionary"] = "Dictionary",
        ["Nav.Settings"] = "Settings",
        ["Nav.EnvironmentMenu"] = "Environment menu",
        ["Nav.EnvironmentStatus"] = "Environment status, view details",
        ["Nav.EnvironmentDetail"] = "Environment details",
        ["Nav.RecheckEnvironment"] = "Re-check environment",

        ["Env.Health.Checking"] = "Checking…",
        ["Env.Health.Healthy"] = "Environment OK",
        ["Env.Health.Degraded"] = "Limited capabilities",
        ["Env.Health.Blocked"] = "Critical dependency missing",
        ["Env.Health.Unknown"] = "Not checked",
        ["Env.Title"] = "Environment",
        ["Env.Recheck"] = "Re-check",
        ["Env.OpenSettings"] = "Open settings",
        ["Env.CopyDiagnostics"] = "Copy diagnostics",

        ["Home.RecognitionLanguage"] = "Language",
        ["Home.Translation"] = "Translation",
        ["Home.StartMeeting"] = "Start meeting",
        // UI-R5B system tray
        ["Tray.StartSession"] = "Start session",
        ["Tray.StopSession"] = "Stop session",
        ["Tray.ShowOverlay"] = "Show subtitle overlay",
        ["Tray.HideOverlay"] = "Hide subtitle overlay",
        ["Tray.OpenSettings"] = "Open settings",
        ["Tray.OpenMainWindow"] = "Open main window",
        ["Tray.Exit"] = "Exit",
        ["Tray.Status.Idle"] = "Idle",
        ["Tray.Status.Starting"] = "Starting",
        ["Tray.Status.Recording"] = "Recording",
        ["Tray.Status.Stopping"] = "Stopping",
        ["Tray.Status.Error"] = "Error",
        ["Tray.MinimizedHint"] = "KikuCaption is still running in the system tray.",
        ["Tray.SessionError"] = "A session error occurred. Open the main window for details.",
        ["General.MinimizeToTray"] = "Hide to the system tray when minimized",
        ["General.CloseToTray"] = "Hide to the system tray when the main window is closed",
        ["Home.Stop"] = "Stop",
        ["Home.ShowOverlay"] = "Show overlay",
        ["Home.HideOverlay"] = "Hide overlay",
        ["Home.NotConfiguredConfigure"] = "Not configured — set up",
        ["Home.LanguageTooltip"] = "Recognition language (cannot change while a session is running)",

        ["Session.Title"] = "Current session",
        ["Session.State"] = "State",
        ["Session.Elapsed"] = "Elapsed",
        ["Session.Language"] = "Language",
        ["Session.Direction"] = "Direction",
        ["Session.Recording"] = "Recording",

        ["Timeline.HeaderPrefix"] = "Meeting captions (",
        ["Timeline.HeaderSuffix"] = " total)",
        ["Timeline.Hint"] = "Oldest on top, newest at the bottom; scrolling up is never interrupted.",
        ["Timeline.Menu"] = "More actions",
        ["Timeline.LoadRecent"] = "Load recent session",
        ["Timeline.ClearDisplay"] = "Clear display",
        ["Timeline.EmptyTitle"] = "No meeting captions yet",
        ["Timeline.EmptyHint"] = "Click “Start meeting” at the top right to begin recording and show live captions.",
        ["Timeline.Recognizing"] = "Recognizing: ",

        ["StartDialog.Title"] = "Start meeting",
        ["StartDialog.Intro"] = "Choose a recording target and start. Captions and the recording are saved to the output folder below.",
        ["StartDialog.CaptureTarget"] = "Recording target:",
        ["StartDialog.WholeScreen"] = "Entire screen",
        ["StartDialog.SpecificWindow"] = "Specific window",
        ["StartDialog.RefreshWindows"] = "Refresh windows",
        ["StartDialog.AudioSection"] = "Audio inputs",
        ["StartDialog.RecordSystemAudio"] = "Record system audio",
        ["StartDialog.RecordMicrophone"] = "Record and recognize my microphone",
        ["StartDialog.MicDevice"] = "Microphone device",
        ["StartDialog.RefreshDevices"] = "Refresh devices",
        ["StartDialog.InputLevel"] = "Input level",
        ["StartDialog.MicTooltip"] = "Microphone recognition uses the current meeting recognition language. When using speakers, the microphone may pick up the system audio again and produce duplicate captions — headphones are recommended.",
        ["StartDialog.NoAudioInput"] = "Select at least one audio input (system audio or microphone).",
        ["StartDialog.MicUnavailable"] = "The selected microphone is unavailable. You can continue with system audio only, or go back and pick another device.",
        ["StartDialog.OutputLocation"] = "Output location",
        ["StartDialog.Cancel"] = "Cancel",
        ["StartDialog.Start"] = "Start meeting",
        ["StartDialog.WindowRequired"] = "“Specific window” is selected — please choose a window to record.",

        ["Audio.Title"] = "Audio tools",
        ["Audio.Intro"] = "Diagnostic tools for verifying system-audio capture and local recognition, independent of the meeting flow.",
        ["Audio.CaptureHeader"] = "System audio capture",
        ["Audio.CaptureIntro"] = "Records system output as 16 kHz / mono / 16-bit PCM WAV. Play audio during capture.",
        ["Audio.StartCapture"] = "Start capture…",
        ["Audio.Stop"] = "Stop",
        ["Audio.RecognizeHeader"] = "Local speech recognition",
        ["Audio.RecognizeIntro"] = "Recognize a WAV file with local faster-whisper, producing time-stamped text. The model loads on first use.",
        ["Audio.RecognitionLanguage"] = "Language:",
        ["Audio.RecognizeWav"] = "Recognize WAV file…",

        ["Settings.Title"] = "Settings",
        ["Settings.Tab.General"] = "General",
        ["Settings.Tab.Subtitle"] = "Captions",
        ["Settings.Tab.Translation"] = "Translation",
        ["Settings.RestoreDefaults"] = "Restore defaults",
        ["Settings.Save"] = "Save",
        ["Settings.Saved"] = "Settings saved.",
        ["Settings.SaveFailed"] = "Could not save settings, please retry.",
        ["Settings.NextMeetingHint"] = "A session is running; changes to language/recording target take effect from the next meeting.",

        ["General.UiLanguage"] = "Interface language",
        ["General.DefaultRecognitionLanguage"] = "Default recognition language",
        ["General.OutputDirectory"] = "Session output folder",
        ["General.Browse"] = "Browse…",
        ["General.LoadRecentOnStartup"] = "Load recent meeting on startup",
        ["General.DefaultTranslationEnabled"] = "Enable translation by default",
        ["General.DefaultRecordingTarget"] = "Default recording target",
        ["General.LogRetentionDays"] = "Log retention (days)",

        ["Subtitle.DefaultShowOverlay"] = "Show overlay by default",
        ["Subtitle.FontSize"] = "Font size",
        ["Subtitle.FontFamily"] = "Font",
        ["Subtitle.BackgroundOpacity"] = "Background opacity",
        ["Subtitle.MaxLines"] = "Max lines",
        ["Subtitle.Topmost"] = "Always on top",
        ["Subtitle.ClickThrough"] = "Click-through",
        ["Subtitle.ShowOriginal"] = "Show original",
        ["Subtitle.ShowTranslation"] = "Show translation",
        ["Subtitle.OriginalColor"] = "Original color",
        ["Subtitle.TranslationColor"] = "Translation color",
        ["Subtitle.PartialOpacity"] = "Dim partial text",
        ["Subtitle.Preview"] = "Live preview",
        ["Subtitle.RestoreDefaults"] = "Restore defaults",
        ["Subtitle.SampleOriginal"] = "これはサンプル字幕です。",
        ["Subtitle.SampleTranslation"] = "This is a sample caption.",
        ["Subtitle.SamplePartial"] = "Partial text being recognized…",

        ["Tr.Header"] = "Translation",
        ["Tr.Intro"] = "Sends only final caption text to the company OpenAI-compatible API. No audio, partial text, or video is sent. The API key is stored DPAPI-encrypted locally, never in config or logs.",
        ["Tr.Enable"] = "Enable translation",
        ["Tr.AuthMode"] = "Auth mode",
        ["Tr.HeaderName"] = "Header name",
        ["Tr.ApiKey"] = "API key",
        ["Tr.SaveKey"] = "Save key",
        ["Tr.ClearKey"] = "Clear key",
        ["Tr.Proxy"] = "Proxy (optional)",
        ["Tr.TestConnection"] = "Test connection",
        ["Tr.SaveSettings"] = "Save settings",
        ["Tr.SourceLanguage"] = "Source",
        ["Tr.SourceFollow"] = "Follow recognition language",
        ["Tr.Timeout"] = "Request timeout (seconds)",
        ["Tr.MaxRetries"] = "Maximum retries",
        ["Tr.TargetLanguage"] = "Target",
        ["Tr.CurrentDirection"] = "Current direction",
        ["Tr.SameLanguageNote"] = "Source and target are the same; no translation is needed.",
        ["Tr.TestSameLanguage"] = "Source and target are the same — choose a different target before testing.",
        ["Home.NoTranslationNeeded"] = "No translation needed: ",
        ["Home.Translating"] = "Translating: ",
        ["Tr.Test.Testing"] = "Testing connection…",
        ["Tr.Test.Success"] = "Connection succeeded.",
        ["Tr.Test.Empty"] = "Connected, but the response was empty.",
        ["Tr.Test.Auth"] = "Authentication failed (check the API key / auth mode).",
        ["Tr.Test.RateLimited"] = "Rate limited (429).",
        ["Tr.Test.Unavailable"] = "Service temporarily unavailable (5xx).",
        ["Tr.Test.Timeout"] = "Connection timed out.",
        ["Tr.Test.Network"] = "Network error.",
        ["Tr.Test.InvalidConfig"] = "Invalid configuration (Endpoint / HTTPS / key).",
        ["Tr.Test.Failed"] = "Connection failed.",
        ["Tr.SettingsSaved"] = "Translation settings saved (endpoint encrypted; loaded automatically next time).",
        ["Tr.SettingsSaveFailed"] = "Could not save translation settings.",
        ["Tr.KeyConfigured"] = "API key: configured",
        ["Tr.KeyNotConfigured"] = "API key: not configured",
        ["Tr.QueueIdle"] = "Idle",
        ["Tr.QueueBusy"] = "Translation queue: {0} in progress",
        ["Tr.LastError"] = "Last error: {0}",

        ["Confirm.CloseWhileRecording"] = "A meeting is being recorded. Closing will stop it safely and save the MP4 and captions (no hard kill). Continue closing?",
        ["Common.AppName"] = "KikuCaption",
        ["Common.NextMeeting"] = "Takes effect next meeting",
        ["Common.AfterRestart"] = "Takes effect after restart",

        ["Session.State.Idle"] = "Idle",
        ["Session.State.Preflight"] = "Preflight",
        ["Session.State.Starting"] = "Starting",
        ["Session.State.Running"] = "Running",
        ["Session.State.Stopping"] = "Stopping",
        ["Session.State.Completed"] = "Completed",
        ["Session.State.Faulted"] = "Faulted",
        ["Session.State.Recovering"] = "Recovering",

        ["Recorder.Ready"] = "Ready",
        ["Recorder.NoFFmpeg"] = "FFmpeg not found (captions only, no recording)",
        ["Recorder.NoFFmpegShort"] = "FFmpeg not found; captions only (no recording).",
        ["Recorder.Unavailable"] = "Recording unavailable (preflight warning) — captions only this session.",
        ["Recorder.Recording"] = "Recording (encoder {0})",
        ["Recorder.Failed"] = "Recording failed; captions only.",
        ["Recorder.Done"] = "Recording complete ({0}, {1} MB)",
        ["Recorder.Incomplete"] = "Recording may be incomplete (see notice).",

        ["Health.Normal"] = "Normal",
        ["Health.HighCpu"] = "High CPU",
        ["Health.LowDisk"] = "Low disk",

        ["Status.Idle"] = "Not started. Once started, system audio is captured and live captions are shown.",
        ["Status.Loading"] = "Starting worker and loading the model (about 1–2 s on first use)…",
        ["Status.Running"] = "Live captions running (language: {0}).",
        ["Status.Stopping"] = "Stopping and saving…",
        ["Status.Stopped"] = "Stopped. Captions saved to the output folder.",
        ["Status.PreflightBlocked"] = "Preflight has blocking issues; not started.",
        ["Status.StartFailed"] = "Start failed; see the message and logs.",
        ["Status.Faulted"] = "Stopped due to an error. Saved captions remain in the output folder.",

        ["Error.StartFailed"] = "Start failed (rolled back started modules; saved captions kept): ",
        ["Error.Fault"] = "Live captioning interrupted: ",
        ["Error.PreflightBlocked"] = "Preflight failed: ",
        ["Error.WindowRequired"] = "“Specific window” is selected — please choose a window to record.",
        ["Error.DiskLow"] = "Low disk space; safely stopped accepting new captions.",
        ["Error.SaveCaptionFailed"] = "Failed to save caption: ",
        ["Error.RecordingStartFailed"] = "Screen recording failed to start: ",
        ["Error.RecordingStopFailed"] = "Error stopping screen recording: ",

        ["Timeline.NewMessages"] = "{0} new captions ↓",
        ["Timeline.Translating"] = "Translating…",
        ["Timeline.TranslationFailed"] = "⚠ Translation failed (original kept)",
        ["Overlay.Translating"] = "Translating…",

        ["Env.Msg.Checking"] = "Checking the environment…",
        ["Env.Msg.Healthy"] = "Environment check complete, no issues found.",
        ["Env.Msg.Degraded"] = "Captions work; some non-critical capabilities (recording or translation) are currently unavailable (see below).",
        ["Env.Msg.Blocked"] = "A critical dependency is missing; core captioning cannot start yet (see below). The app will not crash.",
        ["Env.Msg.Cancelled"] = "Environment check cancelled.",
        ["Env.Msg.Error"] = "The environment check failed; see the logs.",
        ["Env.Msg.NotChecked"] = "The environment has not been checked yet.",
        ["Env.LastChecked"] = "Last checked: {0}",
        ["Env.Copied"] = "Diagnostics copied (no keys or caption text).",
        ["Env.CopyFailed"] = "Could not copy diagnostics, please retry.",

        ["Env.Status.Ok"] = "OK",
        ["Env.Status.Warning"] = "Warning",
        ["Env.Status.Missing"] = "Missing",
        ["Env.Status.Error"] = "Error",
        ["Env.Status.Unknown"] = "Unknown",
        ["Env.Dep.DotNetRuntime"] = ".NET runtime",
        ["Env.Dep.Python"] = "Python",
        ["Env.Dep.WhisperWorker"] = "faster-whisper worker",
        ["Env.Dep.WhisperModel"] = "Whisper model",
        ["Env.Dep.FFmpeg"] = "FFmpeg",
        ["Env.Dep.FFprobe"] = "FFprobe",
        ["Env.Dep.AudioOutputDevice"] = "Audio output device",
        ["Env.Dep.OutputDirectory"] = "Output folder write access",
        ["Env.Dep.DiskSpace"] = "Free disk space",
        ["Env.Dep.TranslationApi"] = "Translation API config",

        ["EnvMsg.DotNet.Ok"] = "Running on the .NET 10 or later runtime.",
        ["EnvMsg.DotNet.Old"] = "The current runtime is older than .NET 10.",
        ["EnvRem.DotNet.Old"] = "Install the .NET 10 runtime / SDK: https://dotnet.microsoft.com/download/dotnet/10.0",
        ["EnvMsg.Python.Ok"] = "A usable Python interpreter was detected (3.11 recommended).",
        ["EnvMsg.Python.OkOldish"] = "Python was detected, but the version may not be fully compatible with faster-whisper; 3.11 is recommended.",
        ["EnvMsg.Python.Missing"] = "Python was not detected. Local speech recognition (faster-whisper) will be unavailable.",
        ["EnvRem.Python.Missing"] = "Install Python 3.11 (tick 'Add to PATH'): https://www.python.org/downloads/",
        ["EnvMsg.FFmpeg.Missing"] = "ffmpeg.exe was not found. Recording and muxing are unavailable, but captioning is unaffected.",
        ["EnvMsg.FFmpeg.NotRunnable"] = "ffmpeg.exe was found but could not run (possibly corrupt or wrong architecture).",
        ["EnvMsg.FFmpeg.Ok"] = "A runnable FFmpeg was detected.",
        ["EnvRem.FFmpeg.Missing"] = "Put ffmpeg.exe in tools/ffmpeg under the app folder, set a path in Settings, or add it to PATH.",
        ["EnvRem.FFmpeg.NotRunnable"] = "Replace it with a working FFmpeg build (64-bit Windows).",
        ["EnvMsg.FFprobe.MissingBeside"] = "ffmpeg.exe was found, but ffprobe.exe is missing from the same folder; muxing will be incomplete.",
        ["EnvMsg.FFprobe.MissingPair"] = "ffprobe.exe was not found (the FFmpeg tool pair is incomplete). Recording is unavailable; captioning is unaffected.",
        ["EnvMsg.FFprobe.NotRunnable"] = "ffprobe.exe was found but could not run (possibly corrupt or wrong architecture).",
        ["EnvMsg.FFprobe.Ok"] = "A runnable FFprobe was detected.",
        ["EnvRem.FFprobe.Missing"] = "Put ffprobe.exe in the same folder as ffmpeg.exe (provide the pair).",
        ["EnvRem.FFprobe.NotRunnable"] = "Replace it with a working FFmpeg build (including a matching ffprobe.exe).",
        ["EnvMsg.Disk.Info"] = "Drive {0} has {1} GB free (minimum required {2} GB).",
        ["EnvMsg.Disk.Error"] = "Could not read the free space of drive {0}.",
        ["EnvRem.Disk.Low"] = "Free disk space is low; clean up or change the output folder before recording.",
        ["EnvRem.Disk.Error"] = "Make sure the output folder's drive exists and is accessible.",
        ["EnvMsg.Worker.NoScript"] = "The whisper_worker script was not found; real-time captions and local recognition cannot run.",
        ["EnvMsg.Worker.NoPython"] = "The worker script was found, but no Python interpreter was found.",
        ["EnvMsg.Worker.Ok"] = "The local recognition worker script and Python interpreter were found.",
        ["EnvRem.Worker.NoScript"] = "Set up the Python environment and ensure the whisper_worker script exists (see the project notes).",
        ["EnvRem.Worker.NoPython"] = "Set the Python executable in Settings, or add it to PATH.",
        ["EnvMsg.Model.Ok"] = "A Whisper model cache was detected.",
        ["EnvMsg.Model.Missing"] = "No Whisper model cache was found; the model must be downloaded before the first recognition.",
        ["EnvRem.Model.Missing"] = "Download the model to the cache folder (default models/whisper) per the project notes.",
        ["EnvMsg.Audio.EnumFail"] = "Could not enumerate audio output devices.",
        ["EnvMsg.Audio.Missing"] = "No default audio output device was detected; system audio cannot be captured.",
        ["EnvMsg.Audio.Ok"] = "A default audio output device was detected.",
        ["EnvRem.Audio.EnumFail"] = "Check the output device in Windows Sound settings.",
        ["EnvRem.Audio.Missing"] = "Enable an output device in Windows Sound settings, then re-check.",
        ["EnvMsg.Output.Ok"] = "The session output folder is writable.",
        ["EnvMsg.Output.NotWritable"] = "Cannot write to the output folder; captions and recordings cannot be saved.",
        ["EnvRem.Output.NotWritable"] = "Choose a writable folder in Settings, or grant write permission to this folder.",
        ["EnvMsg.Trans.Disabled"] = "Translation is disabled (enable it in Settings).",
        ["EnvMsg.Trans.Ok"] = "Translation is configured and available.",
        ["EnvMsg.Trans.Incomplete"] = "Translation is enabled but not fully configured (missing: {0}). Captions are unaffected.",
        ["EnvRem.Trans.Incomplete"] = "Complete the configuration in Translation settings; the key is stored locally, DPAPI-encrypted.",

        ["Capture.screen"] = "Entire screen",
        ["Capture.window"] = "Specific window",
        ["Auth.Bearer"] = "Bearer",
        ["Auth.ApiKeyHeader"] = "API key header",
        ["Auth.None"] = "None",

        // Speech dictionary (UI-R4B)
        ["Dict.Title"] = "Technical dictionary",
        ["Dict.Disclaimer"] = "A dictionary raises the chance the model recognizes these terms, but it does not guarantee they are always transcribed correctly.",
        ["Dict.LanguageFilter"] = "Recognition language",
        ["Dict.New"] = "New",
        ["Dict.Duplicate"] = "Duplicate",
        ["Dict.Delete"] = "Delete",
        ["Dict.SetActive"] = "Set active",
        ["Dict.Save"] = "Save",
        ["Dict.RestoreBuiltIn"] = "Restore default content",
        ["Dict.ActiveMarker"] = "Active",
        ["Dict.BuiltInMarker"] = "Built-in",
        ["Dict.Name"] = "Name",
        ["Dict.Language"] = "Recognition language",
        ["Dict.InitialPrompt"] = "Initial prompt",
        ["Dict.Hotwords"] = "Hotwords",
        ["Dict.HotwordsHint"] = "One term per line",
        ["Dict.ItemsLabel"] = "Items",
        ["Dict.CharsLabel"] = "Characters",
        ["Dict.PromptCharsLabel"] = "Prompt chars",
        ["Dict.AppliesNextMeeting"] = "The change applies to the next meeting.",
        ["Dict.LocalStorageNote"] = "Dictionaries are stored in your local user profile on this machine and are never sent to the translation API.",
        ["Dict.BuiltInReadOnlyHint"] = "Built-in dictionaries are read-only. Click Duplicate to create an editable copy.",
        ["Dict.NewName"] = "New dictionary",
        ["Dict.CopySuffix"] = "Copy",
        ["Dict.Saved"] = "Saved",
        ["Dict.Deleted"] = "Deleted",
        ["Dict.Restored"] = "Default content restored",
        ["Dict.UnsavedTitle"] = "Unsaved changes",
        ["Dict.UnsavedMessage"] = "This dictionary has unsaved changes. Yes = save, No = discard, Cancel = keep editing.",
        ["Dict.DeleteConfirmTitle"] = "Delete dictionary",
        ["Dict.DeleteConfirmMessage"] = "Delete this dictionary? This cannot be undone.",
        ["Dict.DeleteActiveMessage"] = "This is the active dictionary for this language. Deleting it falls back to the built-in default. Delete anyway?",
        ["Dict.BuiltIn.ja"] = "Default Japanese technical dictionary",
        ["Dict.BuiltIn.zh"] = "Default Chinese technical dictionary",
        ["Dict.Error.NameRequired"] = "Name is required.",
        ["Dict.Error.NameLength"] = "Name length {0} exceeds the limit of {1}.",
        ["Dict.Error.NameDuplicate"] = "A dictionary named \"{0}\" already exists for this language.",
        ["Dict.Error.HotwordLength"] = "Term \"{0}\" length {1} exceeds the limit of {2}.",
        ["Dict.Error.HotwordCount"] = "Term count {0} exceeds the limit of {1}.",
        ["Dict.Error.HotwordTotal"] = "Total term characters {0} exceed the limit of {1}.",
        ["Dict.Error.PromptLength"] = "Initial prompt length {0} exceeds the limit of {1}.",

        // Language display names (culture-dependent: English UI uses English names)
        ["Lang.ja"] = "Japanese",
        ["Lang.zh"] = "Chinese",
        ["Lang.en"] = "English"
    };

    private static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>
    {
        ["Nav.Home"] = "ホーム",
        ["Nav.Audio"] = "オーディオ",
        ["Nav.Dictionary"] = "辞書",
        ["Nav.Settings"] = "設定",
        ["Nav.EnvironmentMenu"] = "環境メニュー",
        ["Nav.EnvironmentStatus"] = "環境の状態、詳細を表示",
        ["Nav.EnvironmentDetail"] = "環境の詳細",
        ["Nav.RecheckEnvironment"] = "環境を再確認",

        ["Env.Health.Checking"] = "確認中…",
        ["Env.Health.Healthy"] = "環境は正常です",
        ["Env.Health.Degraded"] = "一部機能が制限されています",
        ["Env.Health.Blocked"] = "重要な環境が不足しています",
        ["Env.Health.Unknown"] = "未確認",
        ["Env.Title"] = "実行環境",
        ["Env.Recheck"] = "再確認",
        ["Env.OpenSettings"] = "設定を開く",
        ["Env.CopyDiagnostics"] = "診断情報をコピー",

        ["Home.RecognitionLanguage"] = "認識言語",
        ["Home.Translation"] = "翻訳",
        ["Home.StartMeeting"] = "会議を開始",
        // UI-R5B system tray
        ["Tray.StartSession"] = "会話を開始",
        ["Tray.StopSession"] = "会話を停止",
        ["Tray.ShowOverlay"] = "字幕オーバーレイを表示",
        ["Tray.HideOverlay"] = "字幕オーバーレイを非表示",
        ["Tray.OpenSettings"] = "設定を開く",
        ["Tray.OpenMainWindow"] = "メインウィンドウを開く",
        ["Tray.Exit"] = "終了",
        ["Tray.Status.Idle"] = "待機中",
        ["Tray.Status.Starting"] = "起動中",
        ["Tray.Status.Recording"] = "録画中",
        ["Tray.Status.Stopping"] = "停止中",
        ["Tray.Status.Error"] = "エラー",
        ["Tray.MinimizedHint"] = "KikuCaption はシステムトレイで実行中です。",
        ["Tray.SessionError"] = "セッションでエラーが発生しました。詳細はメインウィンドウを開いてください。",
        ["General.MinimizeToTray"] = "最小化時にシステムトレイへ隠す",
        ["General.CloseToTray"] = "メインウィンドウを閉じたときにシステムトレイへ隠す",
        ["Home.Stop"] = "停止",
        ["Home.ShowOverlay"] = "字幕を表示",
        ["Home.HideOverlay"] = "字幕を非表示",
        ["Home.NotConfiguredConfigure"] = "未設定（クリックして設定）",
        ["Home.LanguageTooltip"] = "認識言語を選択（会議の実行中は変更できません）",

        ["Session.Title"] = "現在のセッション",
        ["Session.State"] = "状態",
        ["Session.Elapsed"] = "経過時間",
        ["Session.Language"] = "認識言語",
        ["Session.Direction"] = "翻訳方向",
        ["Session.Recording"] = "録画",

        ["Timeline.HeaderPrefix"] = "会議字幕（全 ",
        ["Timeline.HeaderSuffix"] = " 件）",
        ["Timeline.Hint"] = "古い順に上から表示。上にスクロールしても中断されません。",
        ["Timeline.Menu"] = "その他の操作",
        ["Timeline.LoadRecent"] = "最近のセッションを読み込む",
        ["Timeline.ClearDisplay"] = "表示をクリア",
        ["Timeline.EmptyTitle"] = "まだ会議字幕はありません",
        ["Timeline.EmptyHint"] = "右上の「会議を開始」をクリックすると、録画を始めてライブ字幕を表示します。",
        ["Timeline.Recognizing"] = "認識中：",

        ["StartDialog.Title"] = "会議を開始",
        ["StartDialog.Intro"] = "録画対象を選んで開始します。字幕と録画は下の出力フォルダーに保存されます。",
        ["StartDialog.CaptureTarget"] = "録画対象：",
        ["StartDialog.WholeScreen"] = "画面全体",
        ["StartDialog.SpecificWindow"] = "指定ウィンドウ",
        ["StartDialog.RefreshWindows"] = "ウィンドウを更新",
        ["StartDialog.AudioSection"] = "音声入力",
        ["StartDialog.RecordSystemAudio"] = "システム音声を録音",
        ["StartDialog.RecordMicrophone"] = "マイクを録音・認識",
        ["StartDialog.MicDevice"] = "マイクデバイス",
        ["StartDialog.RefreshDevices"] = "デバイスを更新",
        ["StartDialog.InputLevel"] = "入力レベル",
        ["StartDialog.MicTooltip"] = "マイクの認識言語は現在の会議の認識言語に従います。スピーカー使用時はマイクがシステム音声を再度拾い、字幕が重複する場合があります。ヘッドホンの使用を推奨します。",
        ["StartDialog.NoAudioInput"] = "システム音声かマイクのいずれかを選択してください。",
        ["StartDialog.MicUnavailable"] = "選択したマイクを使用できません。システム音声のみで続行するか、別のデバイスを選択してください。",
        ["StartDialog.OutputLocation"] = "出力先",
        ["StartDialog.Cancel"] = "キャンセル",
        ["StartDialog.Start"] = "会議を開始",
        ["StartDialog.WindowRequired"] = "「指定ウィンドウ」が選択されています。録画するウィンドウを選んでください。",

        ["Audio.Title"] = "オーディオツール",
        ["Audio.Intro"] = "システム音声のキャプチャとローカル認識を検証する診断ツールです。会議の流れとは独立しています。",
        ["Audio.CaptureHeader"] = "システム音声キャプチャ",
        ["Audio.CaptureIntro"] = "システム出力音声を 16 kHz / モノラル / 16-bit PCM の WAV として録音します。キャプチャ中は音声を再生してください。",
        ["Audio.StartCapture"] = "キャプチャ開始…",
        ["Audio.Stop"] = "停止",
        ["Audio.RecognizeHeader"] = "ローカル音声認識",
        ["Audio.RecognizeIntro"] = "ローカルの faster-whisper で WAV ファイルを認識し、タイムスタンプ付きテキストを出力します。初回はモデルを読み込みます。",
        ["Audio.RecognitionLanguage"] = "認識言語：",
        ["Audio.RecognizeWav"] = "WAV ファイルを認識…",

        ["Settings.Title"] = "設定",
        ["Settings.Tab.General"] = "一般",
        ["Settings.Tab.Subtitle"] = "字幕",
        ["Settings.Tab.Translation"] = "翻訳",
        ["Settings.RestoreDefaults"] = "既定に戻す",
        ["Settings.Save"] = "保存",
        ["Settings.Saved"] = "設定を保存しました。",
        ["Settings.SaveFailed"] = "設定を保存できませんでした。もう一度お試しください。",
        ["Settings.NextMeetingHint"] = "セッションの実行中です。認識言語や録画対象などの変更は次回の会議から有効になります。",

        ["General.UiLanguage"] = "表示言語",
        ["General.DefaultRecognitionLanguage"] = "既定の認識言語",
        ["General.OutputDirectory"] = "セッション出力フォルダー",
        ["General.Browse"] = "参照…",
        ["General.LoadRecentOnStartup"] = "起動時に最近の会議を読み込む",
        ["General.DefaultTranslationEnabled"] = "既定で翻訳を有効にする",
        ["General.DefaultRecordingTarget"] = "既定の録画対象",
        ["General.LogRetentionDays"] = "ログ保持日数",

        ["Subtitle.DefaultShowOverlay"] = "既定で字幕を表示",
        ["Subtitle.FontSize"] = "文字サイズ",
        ["Subtitle.FontFamily"] = "フォント",
        ["Subtitle.BackgroundOpacity"] = "背景の不透明度",
        ["Subtitle.MaxLines"] = "最大行数",
        ["Subtitle.Topmost"] = "最前面に表示",
        ["Subtitle.ClickThrough"] = "マウス操作を透過",
        ["Subtitle.ShowOriginal"] = "原文を表示",
        ["Subtitle.ShowTranslation"] = "翻訳を表示",
        ["Subtitle.OriginalColor"] = "原文の色",
        ["Subtitle.TranslationColor"] = "翻訳の色",
        ["Subtitle.PartialOpacity"] = "暫定テキストを淡色化",
        ["Subtitle.Preview"] = "リアルタイムプレビュー",
        ["Subtitle.RestoreDefaults"] = "既定値に戻す",
        ["Subtitle.SampleOriginal"] = "これはサンプル字幕です。",
        ["Subtitle.SampleTranslation"] = "これはサンプルの翻訳です。",
        ["Subtitle.SamplePartial"] = "認識中の暫定テキスト…",

        ["Tr.Header"] = "翻訳",
        ["Tr.Intro"] = "final 字幕テキストのみを社内の OpenAI 互換 API に送信して翻訳します。音声・partial・動画は送信しません。API キーは Windows DPAPI で暗号化してローカルに保存し、設定やログには書き込みません。",
        ["Tr.Enable"] = "翻訳を有効にする",
        ["Tr.AuthMode"] = "認証方式",
        ["Tr.HeaderName"] = "ヘッダー名",
        ["Tr.ApiKey"] = "API キー",
        ["Tr.SaveKey"] = "キーを保存",
        ["Tr.ClearKey"] = "キーを削除",
        ["Tr.Proxy"] = "プロキシ（任意）",
        ["Tr.TestConnection"] = "接続テスト",
        ["Tr.SaveSettings"] = "設定を保存",
        ["Tr.SourceLanguage"] = "翻訳元",
        ["Tr.SourceFollow"] = "認識言語に従う",
        ["Tr.Timeout"] = "リクエストタイムアウト（秒）",
        ["Tr.MaxRetries"] = "最大再試行回数",
        ["Tr.TargetLanguage"] = "翻訳先",
        ["Tr.CurrentDirection"] = "現在の方向",
        ["Tr.SameLanguageNote"] = "翻訳元と翻訳先が同じため、翻訳は不要です。",
        ["Tr.TestSameLanguage"] = "翻訳元と翻訳先が同じです。別の翻訳先を選んでからテストしてください。",
        ["Home.NoTranslationNeeded"] = "翻訳不要：",
        ["Home.Translating"] = "翻訳中：",
        ["Tr.Test.Testing"] = "接続をテストしています……",
        ["Tr.Test.Success"] = "接続に成功しました。",
        ["Tr.Test.Empty"] = "接続しましたが、応答が空でした。",
        ["Tr.Test.Auth"] = "認証に失敗しました（API キー／認証方式を確認してください）。",
        ["Tr.Test.RateLimited"] = "レート制限（429）。",
        ["Tr.Test.Unavailable"] = "サービスが一時的に利用できません（5xx）。",
        ["Tr.Test.Timeout"] = "接続がタイムアウトしました。",
        ["Tr.Test.Network"] = "ネットワークエラー。",
        ["Tr.Test.InvalidConfig"] = "設定が無効です（Endpoint / HTTPS / キー）。",
        ["Tr.Test.Failed"] = "接続に失敗しました。",
        ["Tr.SettingsSaved"] = "翻訳設定を保存しました（Endpoint は暗号化され、次回自動的に読み込まれます）。",
        ["Tr.SettingsSaveFailed"] = "翻訳設定の保存に失敗しました。",
        ["Tr.KeyConfigured"] = "API キー：設定済み",
        ["Tr.KeyNotConfigured"] = "API キー：未設定",
        ["Tr.QueueIdle"] = "アイドル",
        ["Tr.QueueBusy"] = "翻訳キュー：{0} 件処理中",
        ["Tr.LastError"] = "最近のエラー：{0}",

        ["Confirm.CloseWhileRecording"] = "会議を録画中です。閉じる前に安全に停止して MP4 と字幕を保存します（強制終了はしません）。閉じてもよろしいですか？",
        ["Common.AppName"] = "KikuCaption",
        ["Common.NextMeeting"] = "次回の会議から有効になります",
        ["Common.AfterRestart"] = "再起動後に有効になります",

        ["Session.State.Idle"] = "アイドル",
        ["Session.State.Preflight"] = "事前確認中",
        ["Session.State.Starting"] = "開始中",
        ["Session.State.Running"] = "実行中",
        ["Session.State.Stopping"] = "停止中",
        ["Session.State.Completed"] = "完了",
        ["Session.State.Faulted"] = "エラー",
        ["Session.State.Recovering"] = "復旧中",

        ["Recorder.Ready"] = "準備完了",
        ["Recorder.NoFFmpeg"] = "FFmpeg が見つかりません（字幕のみ・録画なし）",
        ["Recorder.NoFFmpegShort"] = "FFmpeg が見つかりません。字幕のみ（録画なし）。",
        ["Recorder.Unavailable"] = "録画は利用できません（事前確認の警告）——今回は字幕のみ続行します。",
        ["Recorder.Recording"] = "録画中（エンコーダー {0}）",
        ["Recorder.Failed"] = "録画に失敗しました。字幕のみ続行します。",
        ["Recorder.Done"] = "録画完了（{0}、{1} MB）",
        ["Recorder.Incomplete"] = "録画が不完全な可能性があります（メッセージを参照）。",

        ["Health.Normal"] = "正常",
        ["Health.HighCpu"] = "CPU 高負荷",
        ["Health.LowDisk"] = "ディスク不足",

        ["Status.Idle"] = "未開始。開始するとシステム音声を取り込み、ライブ字幕を表示します。",
        ["Status.Loading"] = "ワーカーを起動しモデルを読み込んでいます（初回は約1〜2秒）……",
        ["Status.Running"] = "ライブ字幕を実行中（言語：{0}）。",
        ["Status.Stopping"] = "停止して保存しています……",
        ["Status.Stopped"] = "停止しました。字幕は出力フォルダーに保存されました。",
        ["Status.PreflightBlocked"] = "事前確認にブロック項目があります。開始しませんでした。",
        ["Status.StartFailed"] = "開始に失敗しました。メッセージとログを参照してください。",
        ["Status.Faulted"] = "エラーにより停止しました。保存済みの字幕は出力フォルダーに残っています。",

        ["Error.StartFailed"] = "開始に失敗しました（開始済みモジュールはロールバック、保存済み字幕は保持）：",
        ["Error.Fault"] = "ライブ字幕が中断されました：",
        ["Error.PreflightBlocked"] = "事前確認に合格しませんでした：",
        ["Error.WindowRequired"] = "「指定ウィンドウ」が選択されています。録画するウィンドウを選んでください。",
        ["Error.DiskLow"] = "ディスク容量が不足しています。新しい字幕の受け付けを安全に停止しました。",
        ["Error.SaveCaptionFailed"] = "字幕の保存に失敗しました：",
        ["Error.RecordingStartFailed"] = "録画の開始に失敗しました：",
        ["Error.RecordingStopFailed"] = "録画の停止でエラーが発生しました：",

        ["Timeline.NewMessages"] = "新しい字幕 {0} 件 ↓",
        ["Timeline.Translating"] = "翻訳中…",
        ["Timeline.TranslationFailed"] = "⚠ 翻訳に失敗しました（原文を保持）",
        ["Overlay.Translating"] = "翻訳中…",

        ["Env.Msg.Checking"] = "環境を確認しています……",
        ["Env.Msg.Healthy"] = "環境の確認が完了しました。問題は見つかりませんでした。",
        ["Env.Msg.Degraded"] = "字幕は利用できます。一部の非重要な機能（録画または翻訳）が現在利用できません（下記参照）。",
        ["Env.Msg.Blocked"] = "重要な依存関係が不足しています。コア字幕機能はまだ開始できません（下記参照）。アプリはクラッシュしません。",
        ["Env.Msg.Cancelled"] = "環境の確認をキャンセルしました。",
        ["Env.Msg.Error"] = "環境の確認でエラーが発生しました。ログを参照してください。",
        ["Env.Msg.NotChecked"] = "実行環境はまだ確認されていません。",
        ["Env.LastChecked"] = "最終確認：{0}",
        ["Env.Copied"] = "診断情報をコピーしました（キーや字幕本文は含みません）。",
        ["Env.CopyFailed"] = "診断情報のコピーに失敗しました。もう一度お試しください。",

        ["Env.Status.Ok"] = "正常",
        ["Env.Status.Warning"] = "注意",
        ["Env.Status.Missing"] = "不足",
        ["Env.Status.Error"] = "エラー",
        ["Env.Status.Unknown"] = "不明",
        ["Env.Dep.DotNetRuntime"] = ".NET ランタイム",
        ["Env.Dep.Python"] = "Python",
        ["Env.Dep.WhisperWorker"] = "faster-whisper ワーカー",
        ["Env.Dep.WhisperModel"] = "Whisper モデル",
        ["Env.Dep.FFmpeg"] = "FFmpeg",
        ["Env.Dep.FFprobe"] = "FFprobe",
        ["Env.Dep.AudioOutputDevice"] = "音声出力デバイス",
        ["Env.Dep.OutputDirectory"] = "出力フォルダーの書き込み権限",
        ["Env.Dep.DiskSpace"] = "空きディスク容量",
        ["Env.Dep.TranslationApi"] = "翻訳 API 設定",

        ["EnvMsg.DotNet.Ok"] = ".NET 10 以降のランタイムで実行しています。",
        ["EnvMsg.DotNet.Old"] = "現在のランタイムは .NET 10 より前です。",
        ["EnvRem.DotNet.Old"] = ".NET 10 ランタイム / SDK をインストールしてください：https://dotnet.microsoft.com/download/dotnet/10.0",
        ["EnvMsg.Python.Ok"] = "利用可能な Python インタープリターを検出しました（3.11 推奨）。",
        ["EnvMsg.Python.OkOldish"] = "Python を検出しましたが、バージョンが faster-whisper と完全には互換でない可能性があります。3.11 を推奨します。",
        ["EnvMsg.Python.Missing"] = "Python を検出できませんでした。ローカル音声認識（faster-whisper）は利用できません。",
        ["EnvRem.Python.Missing"] = "Python 3.11 をインストールしてください（「PATH に追加」にチェック）：https://www.python.org/downloads/",
        ["EnvMsg.FFmpeg.Missing"] = "ffmpeg.exe が見つかりません。録画と多重化は利用できませんが、字幕認識には影響しません。",
        ["EnvMsg.FFmpeg.NotRunnable"] = "ffmpeg.exe は見つかりましたが実行できません（破損またはアーキテクチャ不一致の可能性）。",
        ["EnvMsg.FFmpeg.Ok"] = "実行可能な FFmpeg を検出しました。",
        ["EnvRem.FFmpeg.Missing"] = "アプリフォルダーの tools/ffmpeg に ffmpeg.exe を置くか、設定でパスを指定するか、PATH に追加してください。",
        ["EnvRem.FFmpeg.NotRunnable"] = "動作する FFmpeg ビルド（64 ビット Windows 版）に置き換えてください。",
        ["EnvMsg.FFprobe.MissingBeside"] = "ffmpeg.exe は見つかりましたが、同じフォルダーに ffprobe.exe がありません。多重化が不完全になります。",
        ["EnvMsg.FFprobe.MissingPair"] = "ffprobe.exe が見つかりません（FFmpeg ツールのペアが不完全）。録画は利用できませんが、字幕認識には影響しません。",
        ["EnvMsg.FFprobe.NotRunnable"] = "ffprobe.exe は見つかりましたが実行できません（破損またはアーキテクチャ不一致の可能性）。",
        ["EnvMsg.FFprobe.Ok"] = "実行可能な FFprobe を検出しました。",
        ["EnvRem.FFprobe.Missing"] = "ffprobe.exe を ffmpeg.exe と同じフォルダーに置いてください（ペアで用意）。",
        ["EnvRem.FFprobe.NotRunnable"] = "対応する ffprobe.exe を含む、動作する FFmpeg ビルドに置き換えてください。",
        ["EnvMsg.Disk.Info"] = "ドライブ {0} の空き容量は {1} GB です（最低要件 {2} GB）。",
        ["EnvMsg.Disk.Error"] = "ドライブ {0} の空き容量を読み取れませんでした。",
        ["EnvRem.Disk.Low"] = "空きディスク容量が少なめです。録画前にディスクを整理するか、出力フォルダーを変更してください。",
        ["EnvRem.Disk.Error"] = "出力フォルダーのあるドライブが存在し、アクセスできることを確認してください。",
        ["EnvMsg.Worker.NoScript"] = "whisper_worker スクリプトが見つかりません。リアルタイム字幕とローカル認識は実行できません。",
        ["EnvMsg.Worker.NoPython"] = "ワーカースクリプトは見つかりましたが、Python インタープリターが見つかりません。",
        ["EnvMsg.Worker.Ok"] = "ローカル認識のワーカースクリプトと Python インタープリターが見つかりました。",
        ["EnvRem.Worker.NoScript"] = "Python 環境を用意し、whisper_worker スクリプトが存在することを確認してください（プロジェクトの説明を参照）。",
        ["EnvRem.Worker.NoPython"] = "設定で Python 実行ファイルを指定するか、PATH に追加してください。",
        ["EnvMsg.Model.Ok"] = "Whisper モデルキャッシュを検出しました。",
        ["EnvMsg.Model.Missing"] = "Whisper モデルキャッシュが見つかりません。初回認識の前にモデルのダウンロードが必要です。",
        ["EnvRem.Model.Missing"] = "プロジェクトの説明に従い、キャッシュフォルダー（既定 models/whisper）にモデルをダウンロードしてください。",
        ["EnvMsg.Audio.EnumFail"] = "音声出力デバイスを列挙できませんでした。",
        ["EnvMsg.Audio.Missing"] = "既定の音声出力デバイスを検出できません。システム音声を取り込めません。",
        ["EnvMsg.Audio.Ok"] = "既定の音声出力デバイスを検出しました。",
        ["EnvRem.Audio.EnumFail"] = "Windows のサウンド設定で出力デバイスを確認してください。",
        ["EnvRem.Audio.Missing"] = "Windows のサウンド設定で出力デバイスを有効にしてから、再確認してください。",
        ["EnvMsg.Output.Ok"] = "セッション出力フォルダーに書き込めます。",
        ["EnvMsg.Output.NotWritable"] = "出力フォルダーに書き込めません。字幕と録画ファイルを保存できません。",
        ["EnvRem.Output.NotWritable"] = "設定で書き込み可能なフォルダーに変更するか、このフォルダーに書き込み権限を付与してください。",
        ["EnvMsg.Trans.Disabled"] = "翻訳は無効です（設定で有効にできます）。",
        ["EnvMsg.Trans.Ok"] = "翻訳は設定済みで利用できます。",
        ["EnvMsg.Trans.Incomplete"] = "翻訳は有効ですが設定が不完全です（不足：{0}）。字幕には影響しません。",
        ["EnvRem.Trans.Incomplete"] = "翻訳設定で構成を完成させてください。キーは Windows DPAPI でローカルに暗号化保存されます。",

        ["Capture.screen"] = "画面全体",
        ["Capture.window"] = "指定したウィンドウ",
        ["Auth.Bearer"] = "Bearer",
        ["Auth.ApiKeyHeader"] = "API キーヘッダー",
        ["Auth.None"] = "なし",

        // Speech dictionary (UI-R4B)
        ["Dict.Title"] = "専門用語辞書",
        ["Dict.Disclaimer"] = "辞書はこれらの用語を認識しやすくするためのものですが、毎回正しく認識されることを保証するものではありません。",
        ["Dict.LanguageFilter"] = "認識言語",
        ["Dict.New"] = "新規",
        ["Dict.Duplicate"] = "複製",
        ["Dict.Delete"] = "削除",
        ["Dict.SetActive"] = "現在の辞書に設定",
        ["Dict.Save"] = "保存",
        ["Dict.RestoreBuiltIn"] = "既定の内容に戻す",
        ["Dict.ActiveMarker"] = "使用中",
        ["Dict.BuiltInMarker"] = "内蔵",
        ["Dict.Name"] = "名前",
        ["Dict.Language"] = "認識言語",
        ["Dict.InitialPrompt"] = "初期プロンプト",
        ["Dict.Hotwords"] = "ホットワード",
        ["Dict.HotwordsHint"] = "1行に1語",
        ["Dict.ItemsLabel"] = "項目数",
        ["Dict.CharsLabel"] = "文字数",
        ["Dict.PromptCharsLabel"] = "プロンプト文字",
        ["Dict.AppliesNextMeeting"] = "変更は次回の会議から有効になります。",
        ["Dict.LocalStorageNote"] = "辞書はこのPCの現在のユーザーフォルダーに保存され、翻訳APIには送信されません。",
        ["Dict.BuiltInReadOnlyHint"] = "内蔵辞書は読み取り専用です。編集するには「複製」でユーザー辞書を作成してください。",
        ["Dict.NewName"] = "新しい辞書",
        ["Dict.CopySuffix"] = "コピー",
        ["Dict.Saved"] = "保存しました",
        ["Dict.Deleted"] = "削除しました",
        ["Dict.Restored"] = "既定の内容に戻しました",
        ["Dict.UnsavedTitle"] = "未保存の変更",
        ["Dict.UnsavedMessage"] = "この辞書には未保存の変更があります。「はい」＝保存、「いいえ」＝破棄、「キャンセル」＝編集に戻る。",
        ["Dict.DeleteConfirmTitle"] = "辞書を削除",
        ["Dict.DeleteConfirmMessage"] = "この辞書を削除しますか？この操作は元に戻せません。",
        ["Dict.DeleteActiveMessage"] = "この辞書は現在の言語で使用中です。削除すると内蔵の既定辞書に戻ります。削除しますか？",
        ["Dict.BuiltIn.ja"] = "既定の日本語技術辞書",
        ["Dict.BuiltIn.zh"] = "既定の中国語技術辞書",
        ["Dict.Error.NameRequired"] = "名前を入力してください。",
        ["Dict.Error.NameLength"] = "名前の長さ {0} が上限 {1} を超えています。",
        ["Dict.Error.NameDuplicate"] = "同じ認識言語に「{0}」という辞書が既に存在します。",
        ["Dict.Error.HotwordLength"] = "用語「{0}」の長さ {1} が上限 {2} を超えています。",
        ["Dict.Error.HotwordCount"] = "用語の項目数 {0} が上限 {1} を超えています。",
        ["Dict.Error.HotwordTotal"] = "用語の総文字数 {0} が上限 {1} を超えています。",
        ["Dict.Error.PromptLength"] = "初期プロンプトの長さ {0} が上限 {1} を超えています。",

        // Language display names (Japanese UI)
        ["Lang.ja"] = "日本語",
        ["Lang.zh"] = "中国語",
        ["Lang.en"] = "英語"
    };

    // Declared after Zh/En/Ja so their initializers have run (static field init is textual order).
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Tables { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            [ZhCN] = Zh,
            [EnUS] = En,
            [JaJP] = Ja
        };
}
