using System.Collections.Generic;

namespace KikuCaption.App.Localization;

/// <summary>
/// The bilingual string tables (UI-R3 localization). Keys are stable identifiers; the two tables
/// must contain exactly the same keys — <c>LocalizationResourceTests</c> enforces this. Caption
/// text, meeting files and logs are never translated here. Internal language codes (ja/zh/en) stay
/// stable; only their display names differ per row.
/// </summary>
public static class LocalizedStrings
{
    public const string ZhCN = "zh-CN";
    public const string EnUS = "en-US";
    public const string JaJP = "ja-JP";

    public static IReadOnlyList<string> SupportedCultures { get; } = new[] { ZhCN, EnUS, JaJP };

    private static readonly IReadOnlyDictionary<string, string> Zh = new Dictionary<string, string>
    {
        // Top navigation
        ["Nav.Home"] = "首页",
        ["Nav.Audio"] = "音频",
        ["Nav.Dictionary"] = "词典",
        ["Nav.Settings"] = "设置",
        ["Nav.EnvironmentMenu"] = "环境菜单",
        ["Nav.EnvironmentStatus"] = "环境状态，查看环境详情",
        ["Nav.EnvironmentDetail"] = "环境详情",
        ["Nav.RecheckEnvironment"] = "重新检查环境",

        // Environment health
        ["Env.Health.Checking"] = "正在检查…",
        ["Env.Health.Healthy"] = "环境正常",
        ["Env.Health.Degraded"] = "部分功能受限",
        ["Env.Health.Blocked"] = "关键环境缺失",
        ["Env.Health.Unknown"] = "尚未检查",
        ["Env.Title"] = "运行环境",
        ["Env.Recheck"] = "重新检查",
        ["Env.OpenSettings"] = "打开设置",
        ["Env.CopyDiagnostics"] = "复制诊断信息",

        // Home control bar
        ["Home.RecognitionLanguage"] = "识别语言",
        ["Home.Translation"] = "翻译",
        ["Home.StartMeeting"] = "开始会议",
        ["Home.Stop"] = "停止",
        ["Home.ShowOverlay"] = "显示浮窗",
        ["Home.HideOverlay"] = "隐藏浮窗",
        ["Home.NotConfiguredConfigure"] = "未配置，点此设置",
        ["Home.LanguageTooltip"] = "选择识别语言（会话运行中不可更改）",

        // Session card
        ["Session.Title"] = "当前会话",
        ["Session.State"] = "状态",
        ["Session.Elapsed"] = "已运行",
        ["Session.Language"] = "识别语言",
        ["Session.Direction"] = "翻译方向",
        ["Session.Recording"] = "录制",

        // Timeline
        ["Timeline.HeaderPrefix"] = "会议字幕（全程 ",
        ["Timeline.HeaderSuffix"] = " 条）",
        ["Timeline.Hint"] = "最早在上、最新在下；上滑查看历史不会被打断。",
        ["Timeline.Menu"] = "更多操作",
        ["Timeline.LoadRecent"] = "加载最近会话",
        ["Timeline.ClearDisplay"] = "清空显示",
        ["Timeline.EmptyTitle"] = "还没有会议字幕",
        ["Timeline.EmptyHint"] = "点击右上角“开始会议”，即可开始录制并实时显示字幕。",
        ["Timeline.Recognizing"] = "正在识别：",

        // Start-meeting dialog
        ["StartDialog.Title"] = "开始会议",
        ["StartDialog.Intro"] = "选择录制目标并开始。字幕与录屏会保存到下方输出目录。",
        ["StartDialog.CaptureTarget"] = "录制目标：",
        ["StartDialog.WholeScreen"] = "整个屏幕",
        ["StartDialog.SpecificWindow"] = "指定窗口",
        ["StartDialog.RefreshWindows"] = "刷新窗口",
        ["StartDialog.OutputLocation"] = "输出位置",
        ["StartDialog.Cancel"] = "取消",
        ["StartDialog.Start"] = "开始会议",
        ["StartDialog.WindowRequired"] = "已选择“指定窗口”，请先选择要录制的窗口。",

        // Audio page
        ["Audio.Title"] = "音频工具",
        ["Audio.Intro"] = "用于验证系统音频采集与本地识别的诊断工具，与会议流程独立。",
        ["Audio.CaptureHeader"] = "系统音频捕获",
        ["Audio.CaptureIntro"] = "将系统输出声音录制为 16 kHz / 单声道 / 16-bit PCM 的 WAV。请在捕获期间播放音频。",
        ["Audio.StartCapture"] = "开始捕获…",
        ["Audio.Stop"] = "停止",
        ["Audio.RecognizeHeader"] = "本地语音识别",
        ["Audio.RecognizeIntro"] = "用本地 faster-whisper 识别一个 WAV 文件，输出带时间戳的文本。首次会加载模型。",
        ["Audio.RecognitionLanguage"] = "识别语言：",
        ["Audio.RecognizeWav"] = "识别 WAV 文件…",

        // Settings shell
        ["Settings.Title"] = "设置",
        ["Settings.Tab.General"] = "常用",
        ["Settings.Tab.Subtitle"] = "字幕",
        ["Settings.Tab.Translation"] = "翻译",
        ["Settings.RestoreDefaults"] = "恢复默认设置",
        ["Settings.Save"] = "保存",
        ["Settings.Saved"] = "设置已保存。",
        ["Settings.SaveFailed"] = "保存设置失败，请重试。",
        ["Settings.NextMeetingHint"] = "会话进行中，识别语言/录制目标等更改将于下次会议生效。",

        // General settings
        ["General.UiLanguage"] = "界面语言",
        ["General.DefaultRecognitionLanguage"] = "默认识别语言",
        ["General.OutputDirectory"] = "会话输出目录",
        ["General.Browse"] = "浏览…",
        ["General.LoadRecentOnStartup"] = "启动时加载最近会议",
        ["General.DefaultTranslationEnabled"] = "默认启用翻译",
        ["General.DefaultRecordingTarget"] = "默认录制目标",
        ["General.LogRetentionDays"] = "日志保留天数",

        // Subtitle settings
        ["Subtitle.DefaultShowOverlay"] = "默认显示浮窗",
        ["Subtitle.FontSize"] = "字号",
        ["Subtitle.FontFamily"] = "字体",
        ["Subtitle.BackgroundOpacity"] = "背景透明度",
        ["Subtitle.MaxLines"] = "最大行数",
        ["Subtitle.Topmost"] = "置顶",
        ["Subtitle.ClickThrough"] = "鼠标穿透",
        ["Subtitle.ShowOriginal"] = "显示原文",
        ["Subtitle.ShowTranslation"] = "显示翻译",
        ["Subtitle.OriginalColor"] = "原文颜色",
        ["Subtitle.TranslationColor"] = "翻译颜色",
        ["Subtitle.PartialOpacity"] = "临时文本淡化",
        ["Subtitle.Preview"] = "实时预览",
        ["Subtitle.RestoreDefaults"] = "恢复默认值",
        ["Subtitle.SampleOriginal"] = "これはサンプル字幕です。",
        ["Subtitle.SampleTranslation"] = "这是一条示例字幕。",
        ["Subtitle.SamplePartial"] = "正在识别的临时文本…",

        // Translation settings
        ["Tr.Header"] = "翻译",
        ["Tr.Intro"] = "仅将 final 字幕文本发送到公司内部 OpenAI 兼容 API 翻译。不发送音频、partial 或视频。API Key 以 Windows DPAPI 加密保存在本机，不写入配置或日志。",
        ["Tr.Enable"] = "启用翻译",
        ["Tr.AuthMode"] = "认证模式",
        ["Tr.HeaderName"] = "Header 名",
        ["Tr.ApiKey"] = "API Key",
        ["Tr.SaveKey"] = "保存密钥",
        ["Tr.ClearKey"] = "清除密钥",
        ["Tr.Proxy"] = "代理（可选）",
        ["Tr.TestConnection"] = "测试连接",
        ["Tr.SaveSettings"] = "保存设置",

        // Confirm dialogs
        ["Confirm.CloseWhileRecording"] = "会议正在录制中。关闭前将安全停止并保存 MP4 与字幕（不会强制结束进程）。是否继续关闭？",
        ["Common.AppName"] = "KikuCaption",
        ["Common.NextMeeting"] = "下次会议生效",
        ["Common.AfterRestart"] = "下次启动生效",

        // Session state (from the session state machine; internal enum stays stable)
        ["Session.State.Idle"] = "空闲",
        ["Session.State.Preflight"] = "预检中",
        ["Session.State.Starting"] = "启动中",
        ["Session.State.Running"] = "运行中",
        ["Session.State.Stopping"] = "停止中",
        ["Session.State.Completed"] = "已完成",
        ["Session.State.Faulted"] = "已故障",
        ["Session.State.Recovering"] = "恢复中",

        // Recording status
        ["Recorder.Ready"] = "就绪",
        ["Recorder.NoFFmpeg"] = "未找到 FFmpeg（仅字幕，不录屏）",
        ["Recorder.NoFFmpegShort"] = "未找到 FFmpeg，仅字幕（未录屏）。",
        ["Recorder.Unavailable"] = "录屏不可用（预检警告）——本次仅字幕继续。",
        ["Recorder.Recording"] = "录屏中（编码器 {0}）",
        ["Recorder.Failed"] = "录屏失败，仅字幕。",
        ["Recorder.Done"] = "录屏完成（{0}，{1} MB）",
        ["Recorder.Incomplete"] = "录屏可能不完整（详见提示）。",

        // Health
        ["Health.Normal"] = "运行正常",
        ["Health.HighCpu"] = "CPU 偏高",
        ["Health.LowDisk"] = "磁盘不足",

        // Session status line
        ["Status.Idle"] = "未开始。开始后将捕获系统声音并显示实时字幕。",
        ["Status.Loading"] = "正在启动 Worker 并加载模型（首次约 1–2 秒）……",
        ["Status.Running"] = "实时字幕运行中（语言：{0}）。",
        ["Status.Stopping"] = "正在停止并保存……",
        ["Status.Stopped"] = "已停止。字幕已保存到输出目录。",
        ["Status.PreflightBlocked"] = "预检存在阻断项，未开始。",
        ["Status.StartFailed"] = "启动失败，详见提示与日志。",
        ["Status.Faulted"] = "已因错误停止。已保存的字幕仍在输出目录。",

        // User-facing error titles (technical detail may be appended, not localized)
        ["Error.StartFailed"] = "启动失败（已回滚已启动模块，已保存字幕保留）：",
        ["Error.Fault"] = "实时字幕中断：",
        ["Error.PreflightBlocked"] = "预检未通过：",
        ["Error.WindowRequired"] = "已选择“指定窗口”，请先选择要录制的窗口。",
        ["Error.DiskLow"] = "磁盘空间不足，已安全停止接收新字幕。",
        ["Error.SaveCaptionFailed"] = "保存字幕失败：",
        ["Error.RecordingStartFailed"] = "录屏启动失败：",
        ["Error.RecordingStopFailed"] = "停止录屏出错：",

        // Timeline dynamic
        ["Timeline.NewMessages"] = "有 {0} 条新字幕 ↓",
        ["Timeline.Translating"] = "翻译中…",
        ["Timeline.TranslationFailed"] = "⚠ 翻译失败（已保留原文）",
        ["Overlay.Translating"] = "翻译中…",

        // Environment page messages
        ["Env.Msg.Checking"] = "正在检查运行环境……",
        ["Env.Msg.Healthy"] = "运行环境检查完成，未发现问题。",
        ["Env.Msg.Degraded"] = "字幕可正常使用；部分非关键能力（录屏或翻译）当前不可用（详见下方）。",
        ["Env.Msg.Blocked"] = "缺少关键依赖，核心字幕功能暂时无法开始（详见下方）。程序不会崩溃。",
        ["Env.Msg.Cancelled"] = "环境检查已取消。",
        ["Env.Msg.Error"] = "环境检查过程出错，详见日志。",
        ["Env.Msg.NotChecked"] = "尚未检查运行环境。",
        ["Env.LastChecked"] = "最近检查：{0}",
        ["Env.Copied"] = "已复制诊断信息（不含任何密钥或字幕内容）。",
        ["Env.CopyFailed"] = "复制诊断信息失败，请重试。",

        // Environment item status badges + dependency display names
        ["Env.Status.Ok"] = "正常",
        ["Env.Status.Warning"] = "注意",
        ["Env.Status.Missing"] = "缺失",
        ["Env.Status.Error"] = "错误",
        ["Env.Status.Unknown"] = "未知",
        ["Env.Dep.DotNetRuntime"] = ".NET 运行时",
        ["Env.Dep.Python"] = "Python",
        ["Env.Dep.WhisperWorker"] = "faster-whisper Worker",
        ["Env.Dep.WhisperModel"] = "Whisper 模型",
        ["Env.Dep.FFmpeg"] = "FFmpeg",
        ["Env.Dep.FFprobe"] = "FFprobe",
        ["Env.Dep.AudioOutputDevice"] = "音频输出设备",
        ["Env.Dep.OutputDirectory"] = "输出目录写入权限",
        ["Env.Dep.DiskSpace"] = "可用磁盘空间",
        ["Env.Dep.TranslationApi"] = "翻译 API 配置",

        // Language display names (culture-dependent: Chinese UI uses endonyms)
        ["Lang.ja"] = "日本語",
        ["Lang.zh"] = "中文",
        ["Lang.en"] = "English"
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["Nav.Home"] = "Home",
        ["Nav.Audio"] = "Audio",
        ["Nav.Dictionary"] = "Dictionary",
        ["Nav.Settings"] = "Settings",
        ["Nav.EnvironmentMenu"] = "Environment menu",
        ["Nav.EnvironmentStatus"] = "Environment status, view details",
        ["Nav.EnvironmentDetail"] = "Environment details",
        ["Nav.RecheckEnvironment"] = "Re-check environment",

        ["Env.Health.Checking"] = "Checking…",
        ["Env.Health.Healthy"] = "Environment OK",
        ["Env.Health.Degraded"] = "Limited capabilities",
        ["Env.Health.Blocked"] = "Critical dependency missing",
        ["Env.Health.Unknown"] = "Not checked",
        ["Env.Title"] = "Environment",
        ["Env.Recheck"] = "Re-check",
        ["Env.OpenSettings"] = "Open settings",
        ["Env.CopyDiagnostics"] = "Copy diagnostics",

        ["Home.RecognitionLanguage"] = "Language",
        ["Home.Translation"] = "Translation",
        ["Home.StartMeeting"] = "Start meeting",
        ["Home.Stop"] = "Stop",
        ["Home.ShowOverlay"] = "Show overlay",
        ["Home.HideOverlay"] = "Hide overlay",
        ["Home.NotConfiguredConfigure"] = "Not configured — set up",
        ["Home.LanguageTooltip"] = "Recognition language (cannot change while a session is running)",

        ["Session.Title"] = "Current session",
        ["Session.State"] = "State",
        ["Session.Elapsed"] = "Elapsed",
        ["Session.Language"] = "Language",
        ["Session.Direction"] = "Direction",
        ["Session.Recording"] = "Recording",

        ["Timeline.HeaderPrefix"] = "Meeting captions (",
        ["Timeline.HeaderSuffix"] = " total)",
        ["Timeline.Hint"] = "Oldest on top, newest at the bottom; scrolling up is never interrupted.",
        ["Timeline.Menu"] = "More actions",
        ["Timeline.LoadRecent"] = "Load recent session",
        ["Timeline.ClearDisplay"] = "Clear display",
        ["Timeline.EmptyTitle"] = "No meeting captions yet",
        ["Timeline.EmptyHint"] = "Click “Start meeting” at the top right to begin recording and show live captions.",
        ["Timeline.Recognizing"] = "Recognizing: ",

        ["StartDialog.Title"] = "Start meeting",
        ["StartDialog.Intro"] = "Choose a recording target and start. Captions and the recording are saved to the output folder below.",
        ["StartDialog.CaptureTarget"] = "Recording target:",
        ["StartDialog.WholeScreen"] = "Entire screen",
        ["StartDialog.SpecificWindow"] = "Specific window",
        ["StartDialog.RefreshWindows"] = "Refresh windows",
        ["StartDialog.OutputLocation"] = "Output location",
        ["StartDialog.Cancel"] = "Cancel",
        ["StartDialog.Start"] = "Start meeting",
        ["StartDialog.WindowRequired"] = "“Specific window” is selected — please choose a window to record.",

        ["Audio.Title"] = "Audio tools",
        ["Audio.Intro"] = "Diagnostic tools for verifying system-audio capture and local recognition, independent of the meeting flow.",
        ["Audio.CaptureHeader"] = "System audio capture",
        ["Audio.CaptureIntro"] = "Records system output as 16 kHz / mono / 16-bit PCM WAV. Play audio during capture.",
        ["Audio.StartCapture"] = "Start capture…",
        ["Audio.Stop"] = "Stop",
        ["Audio.RecognizeHeader"] = "Local speech recognition",
        ["Audio.RecognizeIntro"] = "Recognize a WAV file with local faster-whisper, producing time-stamped text. The model loads on first use.",
        ["Audio.RecognitionLanguage"] = "Language:",
        ["Audio.RecognizeWav"] = "Recognize WAV file…",

        ["Settings.Title"] = "Settings",
        ["Settings.Tab.General"] = "General",
        ["Settings.Tab.Subtitle"] = "Captions",
        ["Settings.Tab.Translation"] = "Translation",
        ["Settings.RestoreDefaults"] = "Restore defaults",
        ["Settings.Save"] = "Save",
        ["Settings.Saved"] = "Settings saved.",
        ["Settings.SaveFailed"] = "Could not save settings, please retry.",
        ["Settings.NextMeetingHint"] = "A session is running; changes to language/recording target take effect from the next meeting.",

        ["General.UiLanguage"] = "Interface language",
        ["General.DefaultRecognitionLanguage"] = "Default recognition language",
        ["General.OutputDirectory"] = "Session output folder",
        ["General.Browse"] = "Browse…",
        ["General.LoadRecentOnStartup"] = "Load recent meeting on startup",
        ["General.DefaultTranslationEnabled"] = "Enable translation by default",
        ["General.DefaultRecordingTarget"] = "Default recording target",
        ["General.LogRetentionDays"] = "Log retention (days)",

        ["Subtitle.DefaultShowOverlay"] = "Show overlay by default",
        ["Subtitle.FontSize"] = "Font size",
        ["Subtitle.FontFamily"] = "Font",
        ["Subtitle.BackgroundOpacity"] = "Background opacity",
        ["Subtitle.MaxLines"] = "Max lines",
        ["Subtitle.Topmost"] = "Always on top",
        ["Subtitle.ClickThrough"] = "Click-through",
        ["Subtitle.ShowOriginal"] = "Show original",
        ["Subtitle.ShowTranslation"] = "Show translation",
        ["Subtitle.OriginalColor"] = "Original color",
        ["Subtitle.TranslationColor"] = "Translation color",
        ["Subtitle.PartialOpacity"] = "Dim partial text",
        ["Subtitle.Preview"] = "Live preview",
        ["Subtitle.RestoreDefaults"] = "Restore defaults",
        ["Subtitle.SampleOriginal"] = "これはサンプル字幕です。",
        ["Subtitle.SampleTranslation"] = "This is a sample caption.",
        ["Subtitle.SamplePartial"] = "Partial text being recognized…",

        ["Tr.Header"] = "Translation",
        ["Tr.Intro"] = "Sends only final caption text to the company OpenAI-compatible API. No audio, partial text, or video is sent. The API key is stored DPAPI-encrypted locally, never in config or logs.",
        ["Tr.Enable"] = "Enable translation",
        ["Tr.AuthMode"] = "Auth mode",
        ["Tr.HeaderName"] = "Header name",
        ["Tr.ApiKey"] = "API key",
        ["Tr.SaveKey"] = "Save key",
        ["Tr.ClearKey"] = "Clear key",
        ["Tr.Proxy"] = "Proxy (optional)",
        ["Tr.TestConnection"] = "Test connection",
        ["Tr.SaveSettings"] = "Save settings",

        ["Confirm.CloseWhileRecording"] = "A meeting is being recorded. Closing will stop it safely and save the MP4 and captions (no hard kill). Continue closing?",
        ["Common.AppName"] = "KikuCaption",
        ["Common.NextMeeting"] = "Takes effect next meeting",
        ["Common.AfterRestart"] = "Takes effect after restart",

        ["Session.State.Idle"] = "Idle",
        ["Session.State.Preflight"] = "Preflight",
        ["Session.State.Starting"] = "Starting",
        ["Session.State.Running"] = "Running",
        ["Session.State.Stopping"] = "Stopping",
        ["Session.State.Completed"] = "Completed",
        ["Session.State.Faulted"] = "Faulted",
        ["Session.State.Recovering"] = "Recovering",

        ["Recorder.Ready"] = "Ready",
        ["Recorder.NoFFmpeg"] = "FFmpeg not found (captions only, no recording)",
        ["Recorder.NoFFmpegShort"] = "FFmpeg not found; captions only (no recording).",
        ["Recorder.Unavailable"] = "Recording unavailable (preflight warning) — captions only this session.",
        ["Recorder.Recording"] = "Recording (encoder {0})",
        ["Recorder.Failed"] = "Recording failed; captions only.",
        ["Recorder.Done"] = "Recording complete ({0}, {1} MB)",
        ["Recorder.Incomplete"] = "Recording may be incomplete (see notice).",

        ["Health.Normal"] = "Normal",
        ["Health.HighCpu"] = "High CPU",
        ["Health.LowDisk"] = "Low disk",

        ["Status.Idle"] = "Not started. Once started, system audio is captured and live captions are shown.",
        ["Status.Loading"] = "Starting worker and loading the model (about 1–2 s on first use)…",
        ["Status.Running"] = "Live captions running (language: {0}).",
        ["Status.Stopping"] = "Stopping and saving…",
        ["Status.Stopped"] = "Stopped. Captions saved to the output folder.",
        ["Status.PreflightBlocked"] = "Preflight has blocking issues; not started.",
        ["Status.StartFailed"] = "Start failed; see the message and logs.",
        ["Status.Faulted"] = "Stopped due to an error. Saved captions remain in the output folder.",

        ["Error.StartFailed"] = "Start failed (rolled back started modules; saved captions kept): ",
        ["Error.Fault"] = "Live captioning interrupted: ",
        ["Error.PreflightBlocked"] = "Preflight failed: ",
        ["Error.WindowRequired"] = "“Specific window” is selected — please choose a window to record.",
        ["Error.DiskLow"] = "Low disk space; safely stopped accepting new captions.",
        ["Error.SaveCaptionFailed"] = "Failed to save caption: ",
        ["Error.RecordingStartFailed"] = "Screen recording failed to start: ",
        ["Error.RecordingStopFailed"] = "Error stopping screen recording: ",

        ["Timeline.NewMessages"] = "{0} new captions ↓",
        ["Timeline.Translating"] = "Translating…",
        ["Timeline.TranslationFailed"] = "⚠ Translation failed (original kept)",
        ["Overlay.Translating"] = "Translating…",

        ["Env.Msg.Checking"] = "Checking the environment…",
        ["Env.Msg.Healthy"] = "Environment check complete, no issues found.",
        ["Env.Msg.Degraded"] = "Captions work; some non-critical capabilities (recording or translation) are currently unavailable (see below).",
        ["Env.Msg.Blocked"] = "A critical dependency is missing; core captioning cannot start yet (see below). The app will not crash.",
        ["Env.Msg.Cancelled"] = "Environment check cancelled.",
        ["Env.Msg.Error"] = "The environment check failed; see the logs.",
        ["Env.Msg.NotChecked"] = "The environment has not been checked yet.",
        ["Env.LastChecked"] = "Last checked: {0}",
        ["Env.Copied"] = "Diagnostics copied (no keys or caption text).",
        ["Env.CopyFailed"] = "Could not copy diagnostics, please retry.",

        ["Env.Status.Ok"] = "OK",
        ["Env.Status.Warning"] = "Warning",
        ["Env.Status.Missing"] = "Missing",
        ["Env.Status.Error"] = "Error",
        ["Env.Status.Unknown"] = "Unknown",
        ["Env.Dep.DotNetRuntime"] = ".NET runtime",
        ["Env.Dep.Python"] = "Python",
        ["Env.Dep.WhisperWorker"] = "faster-whisper worker",
        ["Env.Dep.WhisperModel"] = "Whisper model",
        ["Env.Dep.FFmpeg"] = "FFmpeg",
        ["Env.Dep.FFprobe"] = "FFprobe",
        ["Env.Dep.AudioOutputDevice"] = "Audio output device",
        ["Env.Dep.OutputDirectory"] = "Output folder write access",
        ["Env.Dep.DiskSpace"] = "Free disk space",
        ["Env.Dep.TranslationApi"] = "Translation API config",

        // Language display names (culture-dependent: English UI uses English names)
        ["Lang.ja"] = "Japanese",
        ["Lang.zh"] = "Chinese",
        ["Lang.en"] = "English"
    };

    private static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>
    {
        ["Nav.Home"] = "ホーム",
        ["Nav.Audio"] = "オーディオ",
        ["Nav.Dictionary"] = "辞書",
        ["Nav.Settings"] = "設定",
        ["Nav.EnvironmentMenu"] = "環境メニュー",
        ["Nav.EnvironmentStatus"] = "環境の状態、詳細を表示",
        ["Nav.EnvironmentDetail"] = "環境の詳細",
        ["Nav.RecheckEnvironment"] = "環境を再確認",

        ["Env.Health.Checking"] = "確認中…",
        ["Env.Health.Healthy"] = "環境は正常です",
        ["Env.Health.Degraded"] = "一部機能が制限されています",
        ["Env.Health.Blocked"] = "重要な環境が不足しています",
        ["Env.Health.Unknown"] = "未確認",
        ["Env.Title"] = "実行環境",
        ["Env.Recheck"] = "再確認",
        ["Env.OpenSettings"] = "設定を開く",
        ["Env.CopyDiagnostics"] = "診断情報をコピー",

        ["Home.RecognitionLanguage"] = "認識言語",
        ["Home.Translation"] = "翻訳",
        ["Home.StartMeeting"] = "会議を開始",
        ["Home.Stop"] = "停止",
        ["Home.ShowOverlay"] = "字幕を表示",
        ["Home.HideOverlay"] = "字幕を非表示",
        ["Home.NotConfiguredConfigure"] = "未設定（クリックして設定）",
        ["Home.LanguageTooltip"] = "認識言語を選択（会議の実行中は変更できません）",

        ["Session.Title"] = "現在のセッション",
        ["Session.State"] = "状態",
        ["Session.Elapsed"] = "経過時間",
        ["Session.Language"] = "認識言語",
        ["Session.Direction"] = "翻訳方向",
        ["Session.Recording"] = "録画",

        ["Timeline.HeaderPrefix"] = "会議字幕（全 ",
        ["Timeline.HeaderSuffix"] = " 件）",
        ["Timeline.Hint"] = "古い順に上から表示。上にスクロールしても中断されません。",
        ["Timeline.Menu"] = "その他の操作",
        ["Timeline.LoadRecent"] = "最近のセッションを読み込む",
        ["Timeline.ClearDisplay"] = "表示をクリア",
        ["Timeline.EmptyTitle"] = "まだ会議字幕はありません",
        ["Timeline.EmptyHint"] = "右上の「会議を開始」をクリックすると、録画を始めてライブ字幕を表示します。",
        ["Timeline.Recognizing"] = "認識中：",

        ["StartDialog.Title"] = "会議を開始",
        ["StartDialog.Intro"] = "録画対象を選んで開始します。字幕と録画は下の出力フォルダーに保存されます。",
        ["StartDialog.CaptureTarget"] = "録画対象：",
        ["StartDialog.WholeScreen"] = "画面全体",
        ["StartDialog.SpecificWindow"] = "指定ウィンドウ",
        ["StartDialog.RefreshWindows"] = "ウィンドウを更新",
        ["StartDialog.OutputLocation"] = "出力先",
        ["StartDialog.Cancel"] = "キャンセル",
        ["StartDialog.Start"] = "会議を開始",
        ["StartDialog.WindowRequired"] = "「指定ウィンドウ」が選択されています。録画するウィンドウを選んでください。",

        ["Audio.Title"] = "オーディオツール",
        ["Audio.Intro"] = "システム音声のキャプチャとローカル認識を検証する診断ツールです。会議の流れとは独立しています。",
        ["Audio.CaptureHeader"] = "システム音声キャプチャ",
        ["Audio.CaptureIntro"] = "システム出力音声を 16 kHz / モノラル / 16-bit PCM の WAV として録音します。キャプチャ中は音声を再生してください。",
        ["Audio.StartCapture"] = "キャプチャ開始…",
        ["Audio.Stop"] = "停止",
        ["Audio.RecognizeHeader"] = "ローカル音声認識",
        ["Audio.RecognizeIntro"] = "ローカルの faster-whisper で WAV ファイルを認識し、タイムスタンプ付きテキストを出力します。初回はモデルを読み込みます。",
        ["Audio.RecognitionLanguage"] = "認識言語：",
        ["Audio.RecognizeWav"] = "WAV ファイルを認識…",

        ["Settings.Title"] = "設定",
        ["Settings.Tab.General"] = "一般",
        ["Settings.Tab.Subtitle"] = "字幕",
        ["Settings.Tab.Translation"] = "翻訳",
        ["Settings.RestoreDefaults"] = "既定に戻す",
        ["Settings.Save"] = "保存",
        ["Settings.Saved"] = "設定を保存しました。",
        ["Settings.SaveFailed"] = "設定を保存できませんでした。もう一度お試しください。",
        ["Settings.NextMeetingHint"] = "セッションの実行中です。認識言語や録画対象などの変更は次回の会議から有効になります。",

        ["General.UiLanguage"] = "表示言語",
        ["General.DefaultRecognitionLanguage"] = "既定の認識言語",
        ["General.OutputDirectory"] = "セッション出力フォルダー",
        ["General.Browse"] = "参照…",
        ["General.LoadRecentOnStartup"] = "起動時に最近の会議を読み込む",
        ["General.DefaultTranslationEnabled"] = "既定で翻訳を有効にする",
        ["General.DefaultRecordingTarget"] = "既定の録画対象",
        ["General.LogRetentionDays"] = "ログ保持日数",

        ["Subtitle.DefaultShowOverlay"] = "既定で字幕を表示",
        ["Subtitle.FontSize"] = "文字サイズ",
        ["Subtitle.FontFamily"] = "フォント",
        ["Subtitle.BackgroundOpacity"] = "背景の不透明度",
        ["Subtitle.MaxLines"] = "最大行数",
        ["Subtitle.Topmost"] = "最前面に表示",
        ["Subtitle.ClickThrough"] = "クリックスルー",
        ["Subtitle.ShowOriginal"] = "原文を表示",
        ["Subtitle.ShowTranslation"] = "翻訳を表示",
        ["Subtitle.OriginalColor"] = "原文の色",
        ["Subtitle.TranslationColor"] = "翻訳の色",
        ["Subtitle.PartialOpacity"] = "暫定テキストを淡色化",
        ["Subtitle.Preview"] = "リアルタイムプレビュー",
        ["Subtitle.RestoreDefaults"] = "既定値に戻す",
        ["Subtitle.SampleOriginal"] = "これはサンプル字幕です。",
        ["Subtitle.SampleTranslation"] = "これはサンプルの翻訳です。",
        ["Subtitle.SamplePartial"] = "認識中の暫定テキスト…",

        ["Tr.Header"] = "翻訳",
        ["Tr.Intro"] = "final 字幕テキストのみを社内の OpenAI 互換 API に送信して翻訳します。音声・partial・動画は送信しません。API キーは Windows DPAPI で暗号化してローカルに保存し、設定やログには書き込みません。",
        ["Tr.Enable"] = "翻訳を有効にする",
        ["Tr.AuthMode"] = "認証方式",
        ["Tr.HeaderName"] = "ヘッダー名",
        ["Tr.ApiKey"] = "API キー",
        ["Tr.SaveKey"] = "キーを保存",
        ["Tr.ClearKey"] = "キーを削除",
        ["Tr.Proxy"] = "プロキシ（任意）",
        ["Tr.TestConnection"] = "接続テスト",
        ["Tr.SaveSettings"] = "設定を保存",

        ["Confirm.CloseWhileRecording"] = "会議を録画中です。閉じる前に安全に停止して MP4 と字幕を保存します（強制終了はしません）。閉じてもよろしいですか？",
        ["Common.AppName"] = "KikuCaption",
        ["Common.NextMeeting"] = "次回の会議から有効になります",
        ["Common.AfterRestart"] = "再起動後に有効になります",

        ["Session.State.Idle"] = "アイドル",
        ["Session.State.Preflight"] = "事前確認中",
        ["Session.State.Starting"] = "開始中",
        ["Session.State.Running"] = "実行中",
        ["Session.State.Stopping"] = "停止中",
        ["Session.State.Completed"] = "完了",
        ["Session.State.Faulted"] = "エラー",
        ["Session.State.Recovering"] = "復旧中",

        ["Recorder.Ready"] = "準備完了",
        ["Recorder.NoFFmpeg"] = "FFmpeg が見つかりません（字幕のみ・録画なし）",
        ["Recorder.NoFFmpegShort"] = "FFmpeg が見つかりません。字幕のみ（録画なし）。",
        ["Recorder.Unavailable"] = "録画は利用できません（事前確認の警告）——今回は字幕のみ続行します。",
        ["Recorder.Recording"] = "録画中（エンコーダー {0}）",
        ["Recorder.Failed"] = "録画に失敗しました。字幕のみ続行します。",
        ["Recorder.Done"] = "録画完了（{0}、{1} MB）",
        ["Recorder.Incomplete"] = "録画が不完全な可能性があります（メッセージを参照）。",

        ["Health.Normal"] = "正常",
        ["Health.HighCpu"] = "CPU 高負荷",
        ["Health.LowDisk"] = "ディスク不足",

        ["Status.Idle"] = "未開始。開始するとシステム音声を取り込み、ライブ字幕を表示します。",
        ["Status.Loading"] = "ワーカーを起動しモデルを読み込んでいます（初回は約1〜2秒）……",
        ["Status.Running"] = "ライブ字幕を実行中（言語：{0}）。",
        ["Status.Stopping"] = "停止して保存しています……",
        ["Status.Stopped"] = "停止しました。字幕は出力フォルダーに保存されました。",
        ["Status.PreflightBlocked"] = "事前確認にブロック項目があります。開始しませんでした。",
        ["Status.StartFailed"] = "開始に失敗しました。メッセージとログを参照してください。",
        ["Status.Faulted"] = "エラーにより停止しました。保存済みの字幕は出力フォルダーに残っています。",

        ["Error.StartFailed"] = "開始に失敗しました（開始済みモジュールはロールバック、保存済み字幕は保持）：",
        ["Error.Fault"] = "ライブ字幕が中断されました：",
        ["Error.PreflightBlocked"] = "事前確認に合格しませんでした：",
        ["Error.WindowRequired"] = "「指定ウィンドウ」が選択されています。録画するウィンドウを選んでください。",
        ["Error.DiskLow"] = "ディスク容量が不足しています。新しい字幕の受け付けを安全に停止しました。",
        ["Error.SaveCaptionFailed"] = "字幕の保存に失敗しました：",
        ["Error.RecordingStartFailed"] = "録画の開始に失敗しました：",
        ["Error.RecordingStopFailed"] = "録画の停止でエラーが発生しました：",

        ["Timeline.NewMessages"] = "新しい字幕 {0} 件 ↓",
        ["Timeline.Translating"] = "翻訳中…",
        ["Timeline.TranslationFailed"] = "⚠ 翻訳に失敗しました（原文を保持）",
        ["Overlay.Translating"] = "翻訳中…",

        ["Env.Msg.Checking"] = "環境を確認しています……",
        ["Env.Msg.Healthy"] = "環境の確認が完了しました。問題は見つかりませんでした。",
        ["Env.Msg.Degraded"] = "字幕は利用できます。一部の非重要な機能（録画または翻訳）が現在利用できません（下記参照）。",
        ["Env.Msg.Blocked"] = "重要な依存関係が不足しています。コア字幕機能はまだ開始できません（下記参照）。アプリはクラッシュしません。",
        ["Env.Msg.Cancelled"] = "環境の確認をキャンセルしました。",
        ["Env.Msg.Error"] = "環境の確認でエラーが発生しました。ログを参照してください。",
        ["Env.Msg.NotChecked"] = "実行環境はまだ確認されていません。",
        ["Env.LastChecked"] = "最終確認：{0}",
        ["Env.Copied"] = "診断情報をコピーしました（キーや字幕本文は含みません）。",
        ["Env.CopyFailed"] = "診断情報のコピーに失敗しました。もう一度お試しください。",

        ["Env.Status.Ok"] = "正常",
        ["Env.Status.Warning"] = "注意",
        ["Env.Status.Missing"] = "不足",
        ["Env.Status.Error"] = "エラー",
        ["Env.Status.Unknown"] = "不明",
        ["Env.Dep.DotNetRuntime"] = ".NET ランタイム",
        ["Env.Dep.Python"] = "Python",
        ["Env.Dep.WhisperWorker"] = "faster-whisper ワーカー",
        ["Env.Dep.WhisperModel"] = "Whisper モデル",
        ["Env.Dep.FFmpeg"] = "FFmpeg",
        ["Env.Dep.FFprobe"] = "FFprobe",
        ["Env.Dep.AudioOutputDevice"] = "音声出力デバイス",
        ["Env.Dep.OutputDirectory"] = "出力フォルダーの書き込み権限",
        ["Env.Dep.DiskSpace"] = "空きディスク容量",
        ["Env.Dep.TranslationApi"] = "翻訳 API 設定",

        // Language display names (Japanese UI)
        ["Lang.ja"] = "日本語",
        ["Lang.zh"] = "中国語",
        ["Lang.en"] = "英語"
    };

    // Declared after Zh/En/Ja so their initializers have run (static field init is textual order).
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Tables { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            [ZhCN] = Zh,
            [EnUS] = En,
            [JaJP] = Ja
        };
}
